export const data=[

    {
        "region": "REGION",
        "council": "COUNCIL",
        "death_male": "DEATH MALE",
        "death_female": "DEATH FEMALE",
        "death_total": "DEATH TOTAL",
        "indiscipline_male": "INDISCIPLINE MALE",
        "indiscipline_female": "INDISCIPLINE FEMALE",
        "indiscipline_total":"INDISCIPLINE TOTAL",      
        "pregnancy":"pregnancy FEMALE",
        "pregnancy_total":"pregnancy TOTAL",
        "truancy_male":"TRUANCY MALE",
        "truancy_female":"TRUANCY FEMALE",
        "truancy_total":"TRUANCY TOTAL",
        "total_male":"TOTAL MALE",
        "total_female":"TOTAL FEMALE",
        "grand_total":"GRAND TOTAL",
       
      },
      
        {
          "region": "Arusha",
          "council": "Arusha",
          "death_male": 10,
          "death_female": 4,
          "death_total": 14,
          "indiscipline_male": 25,
          "indiscipline_female": 8,
          "indiscipline_total": 33,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 500,
          "truancy_female": 374,
          "truancy_total": 874,
          "total_male": 535,
          "total_female": 387,
          "grand_total": 922
        },
        {
          "region": "Arusha",
          "council": "Arusha CC",
          "death_male": 6,
          "death_female": 5,
          "death_total": 11,
          "indiscipline_male": 8,
          "indiscipline_female": 0,
          "indiscipline_total": 8,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 88,
          "truancy_female": 76,
          "truancy_total": 164,
          "total_male": 102,
          "total_female": 82,
          "grand_total": 184
        },
        {
          "region": "Arusha",
          "council": "Karatu",
          "death_male": 5,
          "death_female": 1,
          "death_total": 6,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 153,
          "truancy_female": 105,
          "truancy_total": 258,
          "total_male": 158,
          "total_female": 107,
          "grand_total": 265
        },
        {
          "region": "Arusha",
          "council": "Longido",
          "death_male": 6,
          "death_female": 0,
          "death_total": 6,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 6,
          "pregnancy_total": 6,
          "truancy_male": 307,
          "truancy_female": 165,
          "truancy_total": 472,
          "total_male": 313,
          "total_female": 171,
          "grand_total": 484
        },
        {
          "region": "Arusha",
          "council": "Meru",
          "death_male": 1,
          "death_female": 2,
          "death_total": 3,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 52,
          "truancy_female": 47,
          "truancy_total": 99,
          "total_male": 53,
          "total_female": 51,
          "grand_total": 104
        },
        {
          "region": "Arusha",
          "council": "Monduli",
          "death_male": 2,
          "death_female": 1,
          "death_total": 3,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 15,
          "pregnancy_total": 15,
          "truancy_male": 84,
          "truancy_female": 47,
          "truancy_total": 131,
          "total_male": 86,
          "total_female": 63,
          "grand_total": 149
        },
        {
          "region": "Arusha",
          "council": "Ngorongoro",
          "death_male": 6,
          "death_female": 1,
          "death_total": 7,
          "indiscipline_male": 3,
          "indiscipline_female": 0,
          "indiscipline_total": 3,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 79,
          "truancy_female": 61,
          "truancy_total": 140,
          "total_male": 88,
          "total_female": 65,
          "grand_total": 153
        },
        {
          "region": "Dar-es-salaam",
          "council": "Ilala MC",
          "death_male": 14,
          "death_female": 14,
          "death_total": 28,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 133,
          "truancy_female": 135,
          "truancy_total": 268,
          "total_male": 147,
          "total_female": 150,
          "grand_total": 297
        },
        {
          "region": "Dar-es-salaam",
          "council": "Kigamboni MC",
          "death_male": 1,
          "death_female": 2,
          "death_total": 3,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 69,
          "truancy_female": 77,
          "truancy_total": 146,
          "total_male": 70,
          "total_female": 79,
          "grand_total": 149
        },
        {
          "region": "Dar-es-salaam",
          "council": "Kinondoni MC",
          "death_male": 4,
          "death_female": 6,
          "death_total": 10,
          "indiscipline_male": 1,
          "indiscipline_female": 2,
          "indiscipline_total": 3,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 46,
          "truancy_female": 49,
          "truancy_total": 95,
          "total_male": 51,
          "total_female": 59,
          "grand_total": 110
        },
        {
          "region": "Dar-es-salaam",
          "council": "Temeke MC",
          "death_male": 15,
          "death_female": 17,
          "death_total": 32,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 346,
          "truancy_female": 338,
          "truancy_total": 684,
          "total_male": 361,
          "total_female": 356,
          "grand_total": 717
        },
        {
          "region": "Dar-es-salaam",
          "council": "Ubungo MC",
          "death_male": 16,
          "death_female": 3,
          "death_total": 19,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 83,
          "truancy_female": 86,
          "truancy_total": 169,
          "total_male": 99,
          "total_female": 89,
          "grand_total": 188
        },
        {
          "region": "Dodoma",
          "council": "Bahi",
          "death_male": 8,
          "death_female": 3,
          "death_total": 11,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 9,
          "pregnancy_total": 9,
          "truancy_male": 266,
          "truancy_female": 215,
          "truancy_total": 481,
          "total_male": 274,
          "total_female": 227,
          "grand_total": 501
        },
        {
          "region": "Dodoma",
          "council": "Chamwino",
          "death_male": 12,
          "death_female": 8,
          "death_total": 20,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 21,
          "pregnancy_total": 21,
          "truancy_male": 209,
          "truancy_female": 145,
          "truancy_total": 354,
          "total_male": 221,
          "total_female": 174,
          "grand_total": 395
        },
        {
          "region": "Dodoma",
          "council": "Chemba",
          "death_male": 15,
          "death_female": 8,
          "death_total": 23,
          "indiscipline_male": 1,
          "indiscipline_female": 0,
          "indiscipline_total": 1,
          "pregnancy": 5,
          "pregnancy_total": 5,
          "truancy_male": 491,
          "truancy_female": 240,
          "truancy_total": 731,
          "total_male": 507,
          "total_female": 253,
          "grand_total": 760
        },
        {
          "region": "Dodoma",
          "council": "Dodoma MC",
          "death_male": 15,
          "death_female": 10,
          "death_total": 25,
          "indiscipline_male": 1,
          "indiscipline_female": 1,
          "indiscipline_total": 2,
          "pregnancy": 10,
          "pregnancy_total": 10,
          "truancy_male": 98,
          "truancy_female": 76,
          "truancy_total": 174,
          "total_male": 114,
          "total_female": 97,
          "grand_total": 211
        },
        {
          "region": "Dodoma",
          "council": "Kondoa",
          "death_male": 3,
          "death_female": 0,
          "death_total": 3,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 70,
          "truancy_female": 35,
          "truancy_total": 105,
          "total_male": 73,
          "total_female": 38,
          "grand_total": 111
        },
        {
          "region": "Dodoma",
          "council": "Kondoa TC",
          "death_male": 2,
          "death_female": 1,
          "death_total": 3,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 9,
          "truancy_female": 4,
          "truancy_total": 13,
          "total_male": 11,
          "total_female": 6,
          "grand_total": 17
        },
        {
          "region": "Dodoma",
          "council": "Kongwa",
          "death_male": 10,
          "death_female": 6,
          "death_total": 16,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 9,
          "pregnancy_total": 9,
          "truancy_male": 228,
          "truancy_female": 239,
          "truancy_total": 467,
          "total_male": 238,
          "total_female": 254,
          "grand_total": 492
        },
        {
          "region": "Dodoma",
          "council": "Mpwapwa",
          "death_male": 10,
          "death_female": 11,
          "death_total": 21,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 5,
          "pregnancy_total": 5,
          "truancy_male": 1377,
          "truancy_female": 1235,
          "truancy_total": 2612,
          "total_male": 1387,
          "total_female": 1251,
          "grand_total": 2638
        },
        {
          "region": "Geita",
          "council": "Bukombe",
          "death_male": 14,
          "death_female": 7,
          "death_total": 21,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 5,
          "pregnancy_total": 5,
          "truancy_male": 103,
          "truancy_female": 94,
          "truancy_total": 197,
          "total_male": 117,
          "total_female": 106,
          "grand_total": 223
        },
        {
          "region": "Geita",
          "council": "Chato",
          "death_male": 18,
          "death_female": 10,
          "death_total": 28,
          "indiscipline_male": 1,
          "indiscipline_female": 0,
          "indiscipline_total": 1,
          "pregnancy": 18,
          "pregnancy_total": 18,
          "truancy_male": 2343,
          "truancy_female": 2119,
          "truancy_total": 4462,
          "total_male": 2362,
          "total_female": 2147,
          "grand_total": 4509
        },
        {
          "region": "Geita",
          "council": "Geita",
          "death_male": 17,
          "death_female": 15,
          "death_total": 32,
          "indiscipline_male": 2,
          "indiscipline_female": 1,
          "indiscipline_total": 3,
          "pregnancy": 5,
          "pregnancy_total": 5,
          "truancy_male": 3979,
          "truancy_female": 3872,
          "truancy_total": 7851,
          "total_male": 3998,
          "total_female": 3893,
          "grand_total": 7891
        },
        {
          "region": "Geita",
          "council": "Geita TC",
          "death_male": 15,
          "death_female": 4,
          "death_total": 19,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 10,
          "pregnancy_total": 10,
          "truancy_male": 124,
          "truancy_female": 114,
          "truancy_total": 238,
          "total_male": 139,
          "total_female": 128,
          "grand_total": 267
        },
        {
          "region": "Geita",
          "council": "Mbogwe",
          "death_male": 1,
          "death_female": 4,
          "death_total": 5,
          "indiscipline_male": 1,
          "indiscipline_female": 0,
          "indiscipline_total": 1,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 788,
          "truancy_female": 706,
          "truancy_total": 1494,
          "total_male": 790,
          "total_female": 713,
          "grand_total": 1503
        },
        {
          "region": "Geita",
          "council": "Nyang'hwale",
          "death_male": 2,
          "death_female": 5,
          "death_total": 7,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 464,
          "truancy_female": 431,
          "truancy_total": 895,
          "total_male": 466,
          "total_female": 438,
          "grand_total": 904
        },
        {
          "region": "Iringa",
          "council": "Iringa",
          "death_male": 8,
          "death_female": 5,
          "death_total": 13,
          "indiscipline_male": 0,
          "indiscipline_female": 1,
          "indiscipline_total": 1,
          "pregnancy": 5,
          "pregnancy_total": 5,
          "truancy_male": 119,
          "truancy_female": 66,
          "truancy_total": 185,
          "total_male": 127,
          "total_female": 77,
          "grand_total": 204
        },
        {
          "region": "Iringa",
          "council": "Iringa MC",
          "death_male": 2,
          "death_female": 4,
          "death_total": 6,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 10,
          "truancy_female": 4,
          "truancy_total": 14,
          "total_male": 12,
          "total_female": 8,
          "grand_total": 20
        },
        {
          "region": "Iringa",
          "council": "Kilolo",
          "death_male": 6,
          "death_female": 4,
          "death_total": 10,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 326,
          "truancy_female": 126,
          "truancy_total": 452,
          "total_male": 332,
          "total_female": 130,
          "grand_total": 462
        },
        {
          "region": "Iringa",
          "council": "Mafinga TC",
          "death_male": 1,
          "death_female": 2,
          "death_total": 3,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 20,
          "truancy_female": 12,
          "truancy_total": 32,
          "total_male": 21,
          "total_female": 14,
          "grand_total": 35
        },
        {
          "region": "Iringa",
          "council": "Mufindi",
          "death_male": 12,
          "death_female": 11,
          "death_total": 23,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 257,
          "truancy_female": 150,
          "truancy_total": 407,
          "total_male": 269,
          "total_female": 164,
          "grand_total": 433
        },
        {
          "region": "Kagera",
          "council": "Biharamulo",
          "death_male": 22,
          "death_female": 6,
          "death_total": 28,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 2500,
          "truancy_female": 2074,
          "truancy_total": 4574,
          "total_male": 2522,
          "total_female": 2081,
          "grand_total": 4603
        },
        {
          "region": "Kagera",
          "council": "Bukoba",
          "death_male": 10,
          "death_female": 7,
          "death_total": 17,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 70,
          "truancy_female": 65,
          "truancy_total": 135,
          "total_male": 80,
          "total_female": 76,
          "grand_total": 156
        },
        {
          "region": "Kagera",
          "council": "Bukoba MC",
          "death_male": 2,
          "death_female": 5,
          "death_total": 7,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 11,
          "truancy_female": 5,
          "truancy_total": 16,
          "total_male": 13,
          "total_female": 10,
          "grand_total": 23
        },
        {
          "region": "Kagera",
          "council": "Karagwe",
          "death_male": 4,
          "death_female": 5,
          "death_total": 9,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 309,
          "truancy_female": 225,
          "truancy_total": 534,
          "total_male": 313,
          "total_female": 231,
          "grand_total": 544
        },
        {
          "region": "Kagera",
          "council": "Kyerwa",
          "death_male": 10,
          "death_female": 6,
          "death_total": 16,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 156,
          "truancy_female": 139,
          "truancy_total": 295,
          "total_male": 166,
          "total_female": 145,
          "grand_total": 311
        },
        {
          "region": "Kagera",
          "council": "Missenyi",
          "death_male": 10,
          "death_female": 7,
          "death_total": 17,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 121,
          "truancy_female": 118,
          "truancy_total": 239,
          "total_male": 131,
          "total_female": 129,
          "grand_total": 260
        },
        {
          "region": "Kagera",
          "council": "Muleba",
          "death_male": 30,
          "death_female": 28,
          "death_total": 58,
          "indiscipline_male": 4,
          "indiscipline_female": 4,
          "indiscipline_total": 8,
          "pregnancy": 8,
          "pregnancy_total": 8,
          "truancy_male": 1287,
          "truancy_female": 1204,
          "truancy_total": 2491,
          "total_male": 1321,
          "total_female": 1244,
          "grand_total": 2565
        },
        {
          "region": "Kagera",
          "council": "Ngara",
          "death_male": 8,
          "death_female": 3,
          "death_total": 11,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 209,
          "truancy_female": 139,
          "truancy_total": 348,
          "total_male": 217,
          "total_female": 145,
          "grand_total": 362
        },
        {
          "region": "Katavi",
          "council": "Mlele",
          "death_male": 2,
          "death_female": 1,
          "death_total": 3,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 11,
          "truancy_female": 5,
          "truancy_total": 16,
          "total_male": 13,
          "total_female": 7,
          "grand_total": 20
        },
        {
          "region": "Katavi",
          "council": "Mpanda",
          "death_male": 7,
          "death_female": 3,
          "death_total": 10,
          "indiscipline_male": 1,
          "indiscipline_female": 1,
          "indiscipline_total": 2,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 121,
          "truancy_female": 86,
          "truancy_total": 207,
          "total_male": 129,
          "total_female": 94,
          "grand_total": 223
        },
        {
          "region": "Katavi",
          "council": "Mpanda MC",
          "death_male": 2,
          "death_female": 2,
          "death_total": 4,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 181,
          "truancy_female": 174,
          "truancy_total": 355,
          "total_male": 183,
          "total_female": 179,
          "grand_total": 362
        },
        {
          "region": "Katavi",
          "council": "Mpimbwe",
          "death_male": 6,
          "death_female": 5,
          "death_total": 11,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 236,
          "truancy_female": 201,
          "truancy_total": 437,
          "total_male": 242,
          "total_female": 207,
          "grand_total": 449
        },
        {
          "region": "Katavi",
          "council": "Nsimbo",
          "death_male": 7,
          "death_female": 1,
          "death_total": 8,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 8,
          "pregnancy_total": 8,
          "truancy_male": 177,
          "truancy_female": 147,
          "truancy_total": 324,
          "total_male": 184,
          "total_female": 156,
          "grand_total": 340
        },
        {
          "region": "Kigoma",
          "council": "Buhigwe",
          "death_male": 13,
          "death_female": 7,
          "death_total": 20,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 541,
          "truancy_female": 448,
          "truancy_total": 989,
          "total_male": 554,
          "total_female": 455,
          "grand_total": 1009
        },
        {
          "region": "Kigoma",
          "council": "Kakonko",
          "death_male": 3,
          "death_female": 1,
          "death_total": 4,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 31,
          "truancy_female": 17,
          "truancy_total": 48,
          "total_male": 34,
          "total_female": 18,
          "grand_total": 52
        },
        {
          "region": "Kigoma",
          "council": "Kasulu",
          "death_male": 10,
          "death_female": 8,
          "death_total": 18,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 131,
          "truancy_female": 127,
          "truancy_total": 258,
          "total_male": 141,
          "total_female": 135,
          "grand_total": 276
        },
        {
          "region": "Kigoma",
          "council": "Kasulu TC",
          "death_male": 11,
          "death_female": 8,
          "death_total": 19,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 31,
          "truancy_female": 33,
          "truancy_total": 64,
          "total_male": 42,
          "total_female": 45,
          "grand_total": 87
        },
        {
          "region": "Kigoma",
          "council": "Kibondo",
          "death_male": 4,
          "death_female": 2,
          "death_total": 6,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 552,
          "truancy_female": 455,
          "truancy_total": 1007,
          "total_male": 556,
          "total_female": 457,
          "grand_total": 1013
        },
        {
          "region": "Kigoma",
          "council": "Kigoma",
          "death_male": 8,
          "death_female": 6,
          "death_total": 14,
          "indiscipline_male": 0,
          "indiscipline_female": 1,
          "indiscipline_total": 1,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 114,
          "truancy_female": 155,
          "truancy_total": 269,
          "total_male": 122,
          "total_female": 165,
          "grand_total": 287
        },
        {
          "region": "Kigoma",
          "council": "Kigoma/Ujiji MC",
          "death_male": 6,
          "death_female": 1,
          "death_total": 7,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 236,
          "truancy_female": 191,
          "truancy_total": 427,
          "total_male": 242,
          "total_female": 193,
          "grand_total": 435
        },
        {
          "region": "Kigoma",
          "council": "Uvinza",
          "death_male": 19,
          "death_female": 16,
          "death_total": 35,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 1127,
          "truancy_female": 929,
          "truancy_total": 2056,
          "total_male": 1146,
          "total_female": 947,
          "grand_total": 2093
        },
        {
          "region": "Kilimanjaro",
          "council": "Hai",
          "death_male": 15,
          "death_female": 11,
          "death_total": 26,
          "indiscipline_male": 1,
          "indiscipline_female": 0,
          "indiscipline_total": 1,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 183,
          "truancy_female": 162,
          "truancy_total": 345,
          "total_male": 199,
          "total_female": 177,
          "grand_total": 376
        },
        {
          "region": "Kilimanjaro",
          "council": "Moshi",
          "death_male": 6,
          "death_female": 3,
          "death_total": 9,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 291,
          "truancy_female": 247,
          "truancy_total": 538,
          "total_male": 297,
          "total_female": 251,
          "grand_total": 548
        },
        {
          "region": "Kilimanjaro",
          "council": "Moshi MC",
          "death_male": 2,
          "death_female": 0,
          "death_total": 2,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 55,
          "truancy_female": 49,
          "truancy_total": 104,
          "total_male": 57,
          "total_female": 51,
          "grand_total": 108
        },
        {
          "region": "Kilimanjaro",
          "council": "Mwanga",
          "death_male": 10,
          "death_female": 8,
          "death_total": 18,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 163,
          "truancy_female": 106,
          "truancy_total": 269,
          "total_male": 173,
          "total_female": 114,
          "grand_total": 287
        },
        {
          "region": "Kilimanjaro",
          "council": "Rombo",
          "death_male": 8,
          "death_female": 2,
          "death_total": 10,
          "indiscipline_male": 0,
          "indiscipline_female": 1,
          "indiscipline_total": 1,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 162,
          "truancy_female": 114,
          "truancy_total": 276,
          "total_male": 170,
          "total_female": 119,
          "grand_total": 289
        },
        {
          "region": "Kilimanjaro",
          "council": "Same",
          "death_male": 4,
          "death_female": 6,
          "death_total": 10,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 433,
          "truancy_female": 388,
          "truancy_total": 821,
          "total_male": 437,
          "total_female": 396,
          "grand_total": 833
        },
        {
          "region": "Kilimanjaro",
          "council": "Siha",
          "death_male": 2,
          "death_female": 2,
          "death_total": 4,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 51,
          "truancy_female": 39,
          "truancy_total": 90,
          "total_male": 53,
          "total_female": 43,
          "grand_total": 96
        },
        {
          "region": "Lindi",
          "council": "Kilwa",
          "death_male": 11,
          "death_female": 8,
          "death_total": 19,
          "indiscipline_male": 2,
          "indiscipline_female": 0,
          "indiscipline_total": 2,
          "pregnancy": 11,
          "pregnancy_total": 11,
          "truancy_male": 217,
          "truancy_female": 145,
          "truancy_total": 362,
          "total_male": 230,
          "total_female": 164,
          "grand_total": 394
        },
        {
          "region": "Lindi",
          "council": "Lindi",
          "death_male": 10,
          "death_female": 5,
          "death_total": 15,
          "indiscipline_male": 1,
          "indiscipline_female": 2,
          "indiscipline_total": 3,
          "pregnancy": 8,
          "pregnancy_total": 8,
          "truancy_male": 268,
          "truancy_female": 165,
          "truancy_total": 433,
          "total_male": 279,
          "total_female": 180,
          "grand_total": 459
        },
        {
          "region": "Lindi",
          "council": "Lindi MC",
          "death_male": 3,
          "death_female": 0,
          "death_total": 3,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 17,
          "truancy_female": 13,
          "truancy_total": 30,
          "total_male": 20,
          "total_female": 16,
          "grand_total": 36
        },
        {
          "region": "Lindi",
          "council": "Liwale",
          "death_male": 5,
          "death_female": 0,
          "death_total": 5,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 92,
          "truancy_female": 49,
          "truancy_total": 141,
          "total_male": 97,
          "total_female": 49,
          "grand_total": 146
        },
        {
          "region": "Lindi",
          "council": "Nachingwea",
          "death_male": 12,
          "death_female": 2,
          "death_total": 14,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 45,
          "truancy_female": 30,
          "truancy_total": 75,
          "total_male": 57,
          "total_female": 33,
          "grand_total": 90
        },
        {
          "region": "Lindi",
          "council": "Ruangwa",
          "death_male": 7,
          "death_female": 5,
          "death_total": 12,
          "indiscipline_male": 1,
          "indiscipline_female": 1,
          "indiscipline_total": 2,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 163,
          "truancy_female": 86,
          "truancy_total": 249,
          "total_male": 171,
          "total_female": 92,
          "grand_total": 263
        },
        {
          "region": "Manyara",
          "council": "Babati",
          "death_male": 8,
          "death_female": 3,
          "death_total": 11,
          "indiscipline_male": 12,
          "indiscipline_female": 5,
          "indiscipline_total": 17,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 350,
          "truancy_female": 225,
          "truancy_total": 575,
          "total_male": 370,
          "total_female": 234,
          "grand_total": 604
        },
        {
          "region": "Manyara",
          "council": "Babati TC",
          "death_male": 1,
          "death_female": 0,
          "death_total": 1,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 20,
          "truancy_female": 12,
          "truancy_total": 32,
          "total_male": 21,
          "total_female": 12,
          "grand_total": 33
        },
        {
          "region": "Manyara",
          "council": "Hanang",
          "death_male": 6,
          "death_female": 9,
          "death_total": 15,
          "indiscipline_male": 1,
          "indiscipline_female": 1,
          "indiscipline_total": 2,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 1403,
          "truancy_female": 876,
          "truancy_total": 2279,
          "total_male": 1410,
          "total_female": 888,
          "grand_total": 2298
        },
        {
          "region": "Manyara",
          "council": "Kiteto",
          "death_male": 5,
          "death_female": 8,
          "death_total": 13,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 7,
          "pregnancy_total": 7,
          "truancy_male": 130,
          "truancy_female": 114,
          "truancy_total": 244,
          "total_male": 135,
          "total_female": 129,
          "grand_total": 264
        },
        {
          "region": "Manyara",
          "council": "Mbulu",
          "death_male": 1,
          "death_female": 0,
          "death_total": 1,
          "indiscipline_male": 3,
          "indiscipline_female": 1,
          "indiscipline_total": 4,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 607,
          "truancy_female": 336,
          "truancy_total": 943,
          "total_male": 611,
          "total_female": 337,
          "grand_total": 948
        },
        {
          "region": "Manyara",
          "council": "Mbulu TC",
          "death_male": 3,
          "death_female": 1,
          "death_total": 4,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 361,
          "truancy_female": 199,
          "truancy_total": 560,
          "total_male": 364,
          "total_female": 200,
          "grand_total": 564
        },
        {
          "region": "Manyara",
          "council": "Simanjiro",
          "death_male": 4,
          "death_female": 6,
          "death_total": 10,
          "indiscipline_male": 1,
          "indiscipline_female": 0,
          "indiscipline_total": 1,
          "pregnancy": 20,
          "pregnancy_total": 20,
          "truancy_male": 229,
          "truancy_female": 142,
          "truancy_total": 371,
          "total_male": 234,
          "total_female": 168,
          "grand_total": 402
        },
        {
          "region": "Mara",
          "council": "Bunda",
          "death_male": 8,
          "death_female": 2,
          "death_total": 10,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 46,
          "truancy_female": 49,
          "truancy_total": 95,
          "total_male": 54,
          "total_female": 51,
          "grand_total": 105
        },
        {
          "region": "Mara",
          "council": "Bunda TC",
          "death_male": 5,
          "death_female": 1,
          "death_total": 6,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 353,
          "truancy_female": 319,
          "truancy_total": 672,
          "total_male": 358,
          "total_female": 320,
          "grand_total": 678
        },
        {
          "region": "Mara",
          "council": "Butiama",
          "death_male": 15,
          "death_female": 14,
          "death_total": 29,
          "indiscipline_male": 6,
          "indiscipline_female": 0,
          "indiscipline_total": 6,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 1190,
          "truancy_female": 1276,
          "truancy_total": 2466,
          "total_male": 1211,
          "total_female": 1293,
          "grand_total": 2504
        },
        {
          "region": "Mara",
          "council": "Musoma",
          "death_male": 7,
          "death_female": 2,
          "death_total": 9,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 60,
          "truancy_female": 93,
          "truancy_total": 153,
          "total_male": 67,
          "total_female": 98,
          "grand_total": 165
        },
        {
          "region": "Mara",
          "council": "Musoma MC",
          "death_male": 6,
          "death_female": 2,
          "death_total": 8,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 16,
          "truancy_female": 17,
          "truancy_total": 33,
          "total_male": 22,
          "total_female": 20,
          "grand_total": 42
        },
        {
          "region": "Mara",
          "council": "Rorya",
          "death_male": 28,
          "death_female": 18,
          "death_total": 46,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 152,
          "truancy_female": 145,
          "truancy_total": 297,
          "total_male": 180,
          "total_female": 164,
          "grand_total": 344
        },
        {
          "region": "Mara",
          "council": "Serengeti",
          "death_male": 6,
          "death_female": 6,
          "death_total": 12,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 5,
          "pregnancy_total": 5,
          "truancy_male": 483,
          "truancy_female": 473,
          "truancy_total": 956,
          "total_male": 489,
          "total_female": 484,
          "grand_total": 973
        },
        {
          "region": "Mara",
          "council": "Tarime",
          "death_male": 14,
          "death_female": 6,
          "death_total": 20,
          "indiscipline_male": 5,
          "indiscipline_female": 4,
          "indiscipline_total": 9,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 686,
          "truancy_female": 739,
          "truancy_total": 1425,
          "total_male": 705,
          "total_female": 749,
          "grand_total": 1454
        },
        {
          "region": "Mara",
          "council": "Tarime TC",
          "death_male": 5,
          "death_female": 4,
          "death_total": 9,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 145,
          "truancy_female": 110,
          "truancy_total": 255,
          "total_male": 150,
          "total_female": 114,
          "grand_total": 264
        },
        {
          "region": "Mbeya",
          "council": "Busokelo",
          "death_male": 4,
          "death_female": 1,
          "death_total": 5,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 25,
          "truancy_female": 9,
          "truancy_total": 34,
          "total_male": 29,
          "total_female": 11,
          "grand_total": 40
        },
        {
          "region": "Mbeya",
          "council": "Chunya",
          "death_male": 9,
          "death_female": 4,
          "death_total": 13,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 207,
          "truancy_female": 186,
          "truancy_total": 393,
          "total_male": 216,
          "total_female": 191,
          "grand_total": 407
        },
        {
          "region": "Mbeya",
          "council": "Kyela",
          "death_male": 9,
          "death_female": 8,
          "death_total": 17,
          "indiscipline_male": 2,
          "indiscipline_female": 1,
          "indiscipline_total": 3,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 76,
          "truancy_female": 69,
          "truancy_total": 145,
          "total_male": 87,
          "total_female": 82,
          "grand_total": 169
        },
        {
          "region": "Mbeya",
          "council": "Mbarali",
          "death_male": 11,
          "death_female": 4,
          "death_total": 15,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 5,
          "pregnancy_total": 5,
          "truancy_male": 17,
          "truancy_female": 28,
          "truancy_total": 45,
          "total_male": 28,
          "total_female": 37,
          "grand_total": 65
        },
        {
          "region": "Mbeya",
          "council": "Mbeya",
          "death_male": 10,
          "death_female": 4,
          "death_total": 14,
          "indiscipline_male": 5,
          "indiscipline_female": 0,
          "indiscipline_total": 5,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 114,
          "truancy_female": 90,
          "truancy_total": 204,
          "total_male": 129,
          "total_female": 94,
          "grand_total": 223
        },
        {
          "region": "Mbeya",
          "council": "Mbeya CC",
          "death_male": 10,
          "death_female": 3,
          "death_total": 13,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 187,
          "truancy_female": 123,
          "truancy_total": 310,
          "total_male": 197,
          "total_female": 128,
          "grand_total": 325
        },
        {
          "region": "Mbeya",
          "council": "Rungwe",
          "death_male": 14,
          "death_female": 9,
          "death_total": 23,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 296,
          "truancy_female": 190,
          "truancy_total": 486,
          "total_male": 310,
          "total_female": 203,
          "grand_total": 513
        },
        {
          "region": "Morogoro",
          "council": "Gairo",
          "death_male": 5,
          "death_female": 3,
          "death_total": 8,
          "indiscipline_male": 4,
          "indiscipline_female": 0,
          "indiscipline_total": 4,
          "pregnancy": 7,
          "pregnancy_total": 7,
          "truancy_male": 117,
          "truancy_female": 80,
          "truancy_total": 197,
          "total_male": 126,
          "total_female": 90,
          "grand_total": 216
        },
        {
          "region": "Morogoro",
          "council": "Ifakara TC",
          "death_male": 3,
          "death_female": 2,
          "death_total": 5,
          "indiscipline_male": 6,
          "indiscipline_female": 4,
          "indiscipline_total": 10,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 53,
          "truancy_female": 38,
          "truancy_total": 91,
          "total_male": 62,
          "total_female": 46,
          "grand_total": 108
        },
        {
          "region": "Morogoro",
          "council": "Kilombero",
          "death_male": 8,
          "death_female": 8,
          "death_total": 16,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 5,
          "pregnancy_total": 5,
          "truancy_male": 110,
          "truancy_female": 113,
          "truancy_total": 223,
          "total_male": 118,
          "total_female": 126,
          "grand_total": 244
        },
        {
          "region": "Morogoro",
          "council": "Kilosa",
          "death_male": 14,
          "death_female": 10,
          "death_total": 24,
          "indiscipline_male": 0,
          "indiscipline_female": 1,
          "indiscipline_total": 1,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 170,
          "truancy_female": 110,
          "truancy_total": 280,
          "total_male": 184,
          "total_female": 125,
          "grand_total": 309
        },
        {
          "region": "Morogoro",
          "council": "Malinyi",
          "death_male": 12,
          "death_female": 6,
          "death_total": 18,
          "indiscipline_male": 30,
          "indiscipline_female": 13,
          "indiscipline_total": 43,
          "pregnancy": 8,
          "pregnancy_total": 8,
          "truancy_male": 181,
          "truancy_female": 122,
          "truancy_total": 303,
          "total_male": 223,
          "total_female": 149,
          "grand_total": 372
        },
        {
          "region": "Morogoro",
          "council": "Morogoro",
          "death_male": 17,
          "death_female": 14,
          "death_total": 31,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 7,
          "pregnancy_total": 7,
          "truancy_male": 178,
          "truancy_female": 122,
          "truancy_total": 300,
          "total_male": 195,
          "total_female": 143,
          "grand_total": 338
        },
        {
          "region": "Morogoro",
          "council": "Morogoro MC",
          "death_male": 3,
          "death_female": 6,
          "death_total": 9,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 77,
          "truancy_female": 73,
          "truancy_total": 150,
          "total_male": 80,
          "total_female": 81,
          "grand_total": 161
        },
        {
          "region": "Morogoro",
          "council": "Mvomero",
          "death_male": 14,
          "death_female": 2,
          "death_total": 16,
          "indiscipline_male": 41,
          "indiscipline_female": 27,
          "indiscipline_total": 68,
          "pregnancy": 6,
          "pregnancy_total": 6,
          "truancy_male": 273,
          "truancy_female": 233,
          "truancy_total": 506,
          "total_male": 328,
          "total_female": 268,
          "grand_total": 596
        },
        {
          "region": "Morogoro",
          "council": "Ulanga",
          "death_male": 8,
          "death_female": 4,
          "death_total": 12,
          "indiscipline_male": 1,
          "indiscipline_female": 0,
          "indiscipline_total": 1,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 172,
          "truancy_female": 102,
          "truancy_total": 274,
          "total_male": 181,
          "total_female": 109,
          "grand_total": 290
        },
        {
          "region": "Mtwara",
          "council": "Masasi",
          "death_male": 8,
          "death_female": 6,
          "death_total": 14,
          "indiscipline_male": 1,
          "indiscipline_female": 0,
          "indiscipline_total": 1,
          "pregnancy": 5,
          "pregnancy_total": 5,
          "truancy_male": 310,
          "truancy_female": 232,
          "truancy_total": 542,
          "total_male": 319,
          "total_female": 243,
          "grand_total": 562
        },
        {
          "region": "Mtwara",
          "council": "Masasi TC",
          "death_male": 3,
          "death_female": 2,
          "death_total": 5,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 48,
          "truancy_female": 37,
          "truancy_total": 85,
          "total_male": 51,
          "total_female": 39,
          "grand_total": 90
        },
        {
          "region": "Mtwara",
          "council": "Mtwara",
          "death_male": 5,
          "death_female": 3,
          "death_total": 8,
          "indiscipline_male": 1,
          "indiscipline_female": 0,
          "indiscipline_total": 1,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 111,
          "truancy_female": 65,
          "truancy_total": 176,
          "total_male": 117,
          "total_female": 71,
          "grand_total": 188
        },
        {
          "region": "Mtwara",
          "council": "Mtwara Mikindani MC",
          "death_male": 0,
          "death_female": 6,
          "death_total": 6,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 43,
          "truancy_female": 24,
          "truancy_total": 67,
          "total_male": 43,
          "total_female": 33,
          "grand_total": 76
        },
        {
          "region": "Mtwara",
          "council": "Nanyamba",
          "death_male": 6,
          "death_female": 1,
          "death_total": 7,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 177,
          "truancy_female": 133,
          "truancy_total": 310,
          "total_male": 183,
          "total_female": 134,
          "grand_total": 317
        },
        {
          "region": "Mtwara",
          "council": "Nanyumbu",
          "death_male": 3,
          "death_female": 6,
          "death_total": 9,
          "indiscipline_male": 0,
          "indiscipline_female": 1,
          "indiscipline_total": 1,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 35,
          "truancy_female": 18,
          "truancy_total": 53,
          "total_male": 38,
          "total_female": 29,
          "grand_total": 67
        },
        {
          "region": "Mtwara",
          "council": "Newala",
          "death_male": 2,
          "death_female": 5,
          "death_total": 7,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 17,
          "truancy_female": 17,
          "truancy_total": 34,
          "total_male": 19,
          "total_female": 23,
          "grand_total": 42
        },
        {
          "region": "Mtwara",
          "council": "Newala TC",
          "death_male": 1,
          "death_female": 3,
          "death_total": 4,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 12,
          "truancy_female": 11,
          "truancy_total": 23,
          "total_male": 13,
          "total_female": 17,
          "grand_total": 30
        },
        {
          "region": "Mtwara",
          "council": "Tandahimba",
          "death_male": 7,
          "death_female": 7,
          "death_total": 14,
          "indiscipline_male": 0,
          "indiscipline_female": 2,
          "indiscipline_total": 2,
          "pregnancy": 5,
          "pregnancy_total": 5,
          "truancy_male": 56,
          "truancy_female": 50,
          "truancy_total": 106,
          "total_male": 63,
          "total_female": 64,
          "grand_total": 127
        },
        {
          "region": "Mwanza",
          "council": "Buchosa",
          "death_male": 17,
          "death_female": 15,
          "death_total": 32,
          "indiscipline_male": 1,
          "indiscipline_female": 1,
          "indiscipline_total": 2,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 1681,
          "truancy_female": 1932,
          "truancy_total": 3613,
          "total_male": 1699,
          "total_female": 1949,
          "grand_total": 3648
        },
        {
          "region": "Mwanza",
          "council": "Ilemela MC",
          "death_male": 6,
          "death_female": 12,
          "death_total": 18,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 306,
          "truancy_female": 314,
          "truancy_total": 620,
          "total_male": 312,
          "total_female": 329,
          "grand_total": 641
        },
        {
          "region": "Mwanza",
          "council": "Kwimba",
          "death_male": 12,
          "death_female": 8,
          "death_total": 20,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 1481,
          "truancy_female": 1135,
          "truancy_total": 2616,
          "total_male": 1493,
          "total_female": 1145,
          "grand_total": 2638
        },
        {
          "region": "Mwanza",
          "council": "Magu",
          "death_male": 9,
          "death_female": 3,
          "death_total": 12,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 112,
          "truancy_female": 113,
          "truancy_total": 225,
          "total_male": 121,
          "total_female": 120,
          "grand_total": 241
        },
        {
          "region": "Mwanza",
          "council": "Misungwi",
          "death_male": 7,
          "death_female": 4,
          "death_total": 11,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 391,
          "truancy_female": 255,
          "truancy_total": 646,
          "total_male": 398,
          "total_female": 259,
          "grand_total": 657
        },
        {
          "region": "Mwanza",
          "council": "Mwanza CC",
          "death_male": 7,
          "death_female": 11,
          "death_total": 18,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 115,
          "truancy_female": 123,
          "truancy_total": 238,
          "total_male": 122,
          "total_female": 135,
          "grand_total": 257
        },
        {
          "region": "Mwanza",
          "council": "Sengerema",
          "death_male": 17,
          "death_female": 6,
          "death_total": 23,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 416,
          "truancy_female": 412,
          "truancy_total": 828,
          "total_male": 433,
          "total_female": 422,
          "grand_total": 855
        },
        {
          "region": "Mwanza",
          "council": "Ukerewe",
          "death_male": 18,
          "death_female": 13,
          "death_total": 31,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 5,
          "pregnancy_total": 5,
          "truancy_male": 323,
          "truancy_female": 454,
          "truancy_total": 777,
          "total_male": 341,
          "total_female": 472,
          "grand_total": 813
        },
        {
          "region": "Njombe",
          "council": "Ludewa",
          "death_male": 6,
          "death_female": 5,
          "death_total": 11,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 58,
          "truancy_female": 37,
          "truancy_total": 95,
          "total_male": 64,
          "total_female": 46,
          "grand_total": 110
        },
        {
          "region": "Njombe",
          "council": "Makambako TC",
          "death_male": 1,
          "death_female": 2,
          "death_total": 3,
          "indiscipline_male": 1,
          "indiscipline_female": 0,
          "indiscipline_total": 1,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 2,
          "truancy_female": 1,
          "truancy_total": 3,
          "total_male": 4,
          "total_female": 3,
          "grand_total": 7
        },
        {
          "region": "Njombe",
          "council": "Makete",
          "death_male": 2,
          "death_female": 1,
          "death_total": 3,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 41,
          "truancy_female": 24,
          "truancy_total": 65,
          "total_male": 43,
          "total_female": 25,
          "grand_total": 68
        },
        {
          "region": "Njombe",
          "council": "Njombe",
          "death_male": 2,
          "death_female": 3,
          "death_total": 5,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 61,
          "truancy_female": 46,
          "truancy_total": 107,
          "total_male": 63,
          "total_female": 50,
          "grand_total": 113
        },
        {
          "region": "Njombe",
          "council": "Njombe TC",
          "death_male": 5,
          "death_female": 3,
          "death_total": 8,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 1,
          "truancy_female": 2,
          "truancy_total": 3,
          "total_male": 6,
          "total_female": 5,
          "grand_total": 11
        },
        {
          "region": "Njombe",
          "council": "Wanging'ombe",
          "death_male": 9,
          "death_female": 2,
          "death_total": 11,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 95,
          "truancy_female": 68,
          "truancy_total": 163,
          "total_male": 104,
          "total_female": 71,
          "grand_total": 175
        },
        {
          "region": "Pwani",
          "council": "Bagamoyo",
          "death_male": 2,
          "death_female": 0,
          "death_total": 2,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 13,
          "truancy_female": 18,
          "truancy_total": 31,
          "total_male": 15,
          "total_female": 18,
          "grand_total": 33
        },
        {
          "region": "Pwani",
          "council": "Chalinze",
          "death_male": 11,
          "death_female": 7,
          "death_total": 18,
          "indiscipline_male": 4,
          "indiscipline_female": 0,
          "indiscipline_total": 4,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 296,
          "truancy_female": 240,
          "truancy_total": 536,
          "total_male": 311,
          "total_female": 247,
          "grand_total": 558
        },
        {
          "region": "Pwani",
          "council": "Kibaha",
          "death_male": 3,
          "death_female": 2,
          "death_total": 5,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 10,
          "truancy_female": 11,
          "truancy_total": 21,
          "total_male": 13,
          "total_female": 15,
          "grand_total": 28
        },
        {
          "region": "Pwani",
          "council": "Kibaha TC",
          "death_male": 1,
          "death_female": 1,
          "death_total": 2,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 3,
          "truancy_female": 1,
          "truancy_total": 4,
          "total_male": 4,
          "total_female": 2,
          "grand_total": 6
        },
        {
          "region": "Pwani",
          "council": "Kibiti",
          "death_male": 4,
          "death_female": 5,
          "death_total": 9,
          "indiscipline_male": 1,
          "indiscipline_female": 1,
          "indiscipline_total": 2,
          "pregnancy": 6,
          "pregnancy_total": 6,
          "truancy_male": 311,
          "truancy_female": 242,
          "truancy_total": 553,
          "total_male": 316,
          "total_female": 254,
          "grand_total": 570
        },
        {
          "region": "Pwani",
          "council": "Kisarawe",
          "death_male": 5,
          "death_female": 3,
          "death_total": 8,
          "indiscipline_male": 1,
          "indiscipline_female": 0,
          "indiscipline_total": 1,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 90,
          "truancy_female": 73,
          "truancy_total": 163,
          "total_male": 96,
          "total_female": 77,
          "grand_total": 173
        },
        {
          "region": "Pwani",
          "council": "Mafia",
          "death_male": 1,
          "death_female": 0,
          "death_total": 1,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 15,
          "truancy_female": 6,
          "truancy_total": 21,
          "total_male": 16,
          "total_female": 7,
          "grand_total": 23
        },
        {
          "region": "Pwani",
          "council": "Mkuranga",
          "death_male": 15,
          "death_female": 13,
          "death_total": 28,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 7,
          "pregnancy_total": 7,
          "truancy_male": 271,
          "truancy_female": 239,
          "truancy_total": 510,
          "total_male": 286,
          "total_female": 259,
          "grand_total": 545
        },
        {
          "region": "Pwani",
          "council": "Rufiji",
          "death_male": 5,
          "death_female": 8,
          "death_total": 13,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 96,
          "truancy_female": 71,
          "truancy_total": 167,
          "total_male": 101,
          "total_female": 80,
          "grand_total": 181
        },
        {
          "region": "Rukwa",
          "council": "Kalambo",
          "death_male": 7,
          "death_female": 0,
          "death_total": 7,
          "indiscipline_male": 1,
          "indiscipline_female": 0,
          "indiscipline_total": 1,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 312,
          "truancy_female": 275,
          "truancy_total": 587,
          "total_male": 320,
          "total_female": 276,
          "grand_total": 596
        },
        {
          "region": "Rukwa",
          "council": "Nkasi",
          "death_male": 23,
          "death_female": 8,
          "death_total": 31,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 5,
          "pregnancy_total": 5,
          "truancy_male": 1778,
          "truancy_female": 1772,
          "truancy_total": 3550,
          "total_male": 1801,
          "total_female": 1785,
          "grand_total": 3586
        },
        {
          "region": "Rukwa",
          "council": "Sumbawanga",
          "death_male": 16,
          "death_female": 17,
          "death_total": 33,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 505,
          "truancy_female": 411,
          "truancy_total": 916,
          "total_male": 521,
          "total_female": 430,
          "grand_total": 951
        },
        {
          "region": "Rukwa",
          "council": "Sumbawanga MC",
          "death_male": 4,
          "death_female": 5,
          "death_total": 9,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 290,
          "truancy_female": 215,
          "truancy_total": 505,
          "total_male": 294,
          "total_female": 224,
          "grand_total": 518
        },
        {
          "region": "Ruvuma",
          "council": "Madaba",
          "death_male": 6,
          "death_female": 2,
          "death_total": 8,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 6,
          "truancy_female": 8,
          "truancy_total": 14,
          "total_male": 12,
          "total_female": 12,
          "grand_total": 24
        },
        {
          "region": "Ruvuma",
          "council": "Mbinga",
          "death_male": 5,
          "death_female": 3,
          "death_total": 8,
          "indiscipline_male": 0,
          "indiscipline_female": 1,
          "indiscipline_total": 1,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 10,
          "truancy_female": 9,
          "truancy_total": 19,
          "total_male": 15,
          "total_female": 15,
          "grand_total": 30
        },
        {
          "region": "Ruvuma",
          "council": "Mbinga TC",
          "death_male": 3,
          "death_female": 1,
          "death_total": 4,
          "indiscipline_male": 14,
          "indiscipline_female": 7,
          "indiscipline_total": 21,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 32,
          "truancy_female": 21,
          "truancy_total": 53,
          "total_male": 49,
          "total_female": 29,
          "grand_total": 78
        },
        {
          "region": "Ruvuma",
          "council": "Namtumbo",
          "death_male": 11,
          "death_female": 9,
          "death_total": 20,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 52,
          "truancy_female": 37,
          "truancy_total": 89,
          "total_male": 63,
          "total_female": 47,
          "grand_total": 110
        },
        {
          "region": "Ruvuma",
          "council": "Nyasa",
          "death_male": 4,
          "death_female": 5,
          "death_total": 9,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 20,
          "truancy_female": 9,
          "truancy_total": 29,
          "total_male": 24,
          "total_female": 16,
          "grand_total": 40
        },
        {
          "region": "Ruvuma",
          "council": "Songea",
          "death_male": 7,
          "death_female": 5,
          "death_total": 12,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 5,
          "truancy_female": 8,
          "truancy_total": 13,
          "total_male": 12,
          "total_female": 16,
          "grand_total": 28
        },
        {
          "region": "Ruvuma",
          "council": "Songea MC",
          "death_male": 3,
          "death_female": 4,
          "death_total": 7,
          "indiscipline_male": 1,
          "indiscipline_female": 0,
          "indiscipline_total": 1,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 4,
          "truancy_female": 4,
          "truancy_total": 8,
          "total_male": 8,
          "total_female": 10,
          "grand_total": 18
        },
        {
          "region": "Ruvuma",
          "council": "Tunduru",
          "death_male": 13,
          "death_female": 8,
          "death_total": 21,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 17,
          "pregnancy_total": 17,
          "truancy_male": 104,
          "truancy_female": 51,
          "truancy_total": 155,
          "total_male": 117,
          "total_female": 76,
          "grand_total": 193
        },
        {
          "region": "Shinyanga",
          "council": "Kahama TC",
          "death_male": 14,
          "death_female": 9,
          "death_total": 23,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 83,
          "truancy_female": 38,
          "truancy_total": 121,
          "total_male": 97,
          "total_female": 51,
          "grand_total": 148
        },
        {
          "region": "Shinyanga",
          "council": "Kishapu",
          "death_male": 7,
          "death_female": 6,
          "death_total": 13,
          "indiscipline_male": 0,
          "indiscipline_female": 2,
          "indiscipline_total": 2,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 344,
          "truancy_female": 261,
          "truancy_total": 605,
          "total_male": 351,
          "total_female": 272,
          "grand_total": 623
        },
        {
          "region": "Shinyanga",
          "council": "Msalala",
          "death_male": 14,
          "death_female": 11,
          "death_total": 25,
          "indiscipline_male": 3,
          "indiscipline_female": 0,
          "indiscipline_total": 3,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 618,
          "truancy_female": 545,
          "truancy_total": 1163,
          "total_male": 635,
          "total_female": 560,
          "grand_total": 1195
        },
        {
          "region": "Shinyanga",
          "council": "Shinyanga",
          "death_male": 9,
          "death_female": 6,
          "death_total": 15,
          "indiscipline_male": 1,
          "indiscipline_female": 0,
          "indiscipline_total": 1,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 187,
          "truancy_female": 170,
          "truancy_total": 357,
          "total_male": 197,
          "total_female": 179,
          "grand_total": 376
        },
        {
          "region": "Shinyanga",
          "council": "Shinyanga MC",
          "death_male": 8,
          "death_female": 6,
          "death_total": 14,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 101,
          "truancy_female": 97,
          "truancy_total": 198,
          "total_male": 109,
          "total_female": 106,
          "grand_total": 215
        },
        {
          "region": "Shinyanga",
          "council": "Ushetu",
          "death_male": 16,
          "death_female": 12,
          "death_total": 28,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 91,
          "truancy_female": 92,
          "truancy_total": 183,
          "total_male": 107,
          "total_female": 106,
          "grand_total": 213
        },
        {
          "region": "Simiyu",
          "council": "Bariadi",
          "death_male": 12,
          "death_female": 14,
          "death_total": 26,
          "indiscipline_male": 0,
          "indiscipline_female": 1,
          "indiscipline_total": 1,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 427,
          "truancy_female": 458,
          "truancy_total": 885,
          "total_male": 439,
          "total_female": 475,
          "grand_total": 914
        },
        {
          "region": "Simiyu",
          "council": "Bariadi TC",
          "death_male": 4,
          "death_female": 3,
          "death_total": 7,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 400,
          "truancy_female": 490,
          "truancy_total": 890,
          "total_male": 404,
          "total_female": 493,
          "grand_total": 897
        },
        {
          "region": "Simiyu",
          "council": "Busega",
          "death_male": 20,
          "death_female": 21,
          "death_total": 41,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 362,
          "truancy_female": 464,
          "truancy_total": 826,
          "total_male": 382,
          "total_female": 489,
          "grand_total": 871
        },
        {
          "region": "Simiyu",
          "council": "Itilima",
          "death_male": 6,
          "death_female": 6,
          "death_total": 12,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 1070,
          "truancy_female": 725,
          "truancy_total": 1795,
          "total_male": 1076,
          "total_female": 731,
          "grand_total": 1807
        },
        {
          "region": "Simiyu",
          "council": "Maswa",
          "death_male": 7,
          "death_female": 7,
          "death_total": 14,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 249,
          "truancy_female": 191,
          "truancy_total": 440,
          "total_male": 256,
          "total_female": 201,
          "grand_total": 457
        },
        {
          "region": "Simiyu",
          "council": "Meatu",
          "death_male": 10,
          "death_female": 4,
          "death_total": 14,
          "indiscipline_male": 4,
          "indiscipline_female": 4,
          "indiscipline_total": 8,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 1361,
          "truancy_female": 1244,
          "truancy_total": 2605,
          "total_male": 1375,
          "total_female": 1254,
          "grand_total": 2629
        },
        {
          "region": "Singida",
          "council": "Ikungi",
          "death_male": 15,
          "death_female": 4,
          "death_total": 19,
          "indiscipline_male": 2,
          "indiscipline_female": 0,
          "indiscipline_total": 2,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 369,
          "truancy_female": 241,
          "truancy_total": 610,
          "total_male": 386,
          "total_female": 248,
          "grand_total": 634
        },
        {
          "region": "Singida",
          "council": "Iramba",
          "death_male": 6,
          "death_female": 6,
          "death_total": 12,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 8,
          "pregnancy_total": 8,
          "truancy_male": 180,
          "truancy_female": 120,
          "truancy_total": 300,
          "total_male": 186,
          "total_female": 134,
          "grand_total": 320
        },
        {
          "region": "Singida",
          "council": "Itigi",
          "death_male": 6,
          "death_female": 6,
          "death_total": 12,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 540,
          "truancy_female": 421,
          "truancy_total": 961,
          "total_male": 546,
          "total_female": 431,
          "grand_total": 977
        },
        {
          "region": "Singida",
          "council": "Manyoni",
          "death_male": 8,
          "death_female": 13,
          "death_total": 21,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 1431,
          "truancy_female": 1131,
          "truancy_total": 2562,
          "total_male": 1439,
          "total_female": 1148,
          "grand_total": 2587
        },
        {
          "region": "Singida",
          "council": "Mkalama",
          "death_male": 3,
          "death_female": 7,
          "death_total": 10,
          "indiscipline_male": 1,
          "indiscipline_female": 0,
          "indiscipline_total": 1,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 225,
          "truancy_female": 128,
          "truancy_total": 353,
          "total_male": 229,
          "total_female": 136,
          "grand_total": 365
        },
        {
          "region": "Singida",
          "council": "Singida",
          "death_male": 1,
          "death_female": 1,
          "death_total": 2,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 276,
          "truancy_female": 161,
          "truancy_total": 437,
          "total_male": 277,
          "total_female": 162,
          "grand_total": 439
        },
        {
          "region": "Singida",
          "council": "Singida MC",
          "death_male": 7,
          "death_female": 2,
          "death_total": 9,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 100,
          "truancy_female": 57,
          "truancy_total": 157,
          "total_male": 107,
          "total_female": 59,
          "grand_total": 166
        },
        {
          "region": "Songwe",
          "council": "Ileje",
          "death_male": 5,
          "death_female": 3,
          "death_total": 8,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 30,
          "truancy_female": 24,
          "truancy_total": 54,
          "total_male": 35,
          "total_female": 27,
          "grand_total": 62
        },
        {
          "region": "Songwe",
          "council": "Mbozi",
          "death_male": 17,
          "death_female": 16,
          "death_total": 33,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 158,
          "truancy_female": 111,
          "truancy_total": 269,
          "total_male": 175,
          "total_female": 131,
          "grand_total": 306
        },
        {
          "region": "Songwe",
          "council": "Momba",
          "death_male": 11,
          "death_female": 9,
          "death_total": 20,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 623,
          "truancy_female": 586,
          "truancy_total": 1209,
          "total_male": 634,
          "total_female": 595,
          "grand_total": 1229
        },
        {
          "region": "Songwe",
          "council": "Songwe",
          "death_male": 7,
          "death_female": 4,
          "death_total": 11,
          "indiscipline_male": 38,
          "indiscipline_female": 8,
          "indiscipline_total": 46,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 606,
          "truancy_female": 618,
          "truancy_total": 1224,
          "total_male": 651,
          "total_female": 631,
          "grand_total": 1282
        },
        {
          "region": "Songwe",
          "council": "Tunduma TC",
          "death_male": 1,
          "death_female": 0,
          "death_total": 1,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 212,
          "truancy_female": 164,
          "truancy_total": 376,
          "total_male": 213,
          "total_female": 164,
          "grand_total": 377
        },
        {
          "region": "Tabora",
          "council": "Igunga",
          "death_male": 25,
          "death_female": 14,
          "death_total": 39,
          "indiscipline_male": 2,
          "indiscipline_female": 3,
          "indiscipline_total": 5,
          "pregnancy": 4,
          "pregnancy_total": 4,
          "truancy_male": 1137,
          "truancy_female": 922,
          "truancy_total": 2059,
          "total_male": 1164,
          "total_female": 943,
          "grand_total": 2107
        },
        {
          "region": "Tabora",
          "council": "Kaliua",
          "death_male": 21,
          "death_female": 12,
          "death_total": 33,
          "indiscipline_male": 3,
          "indiscipline_female": 0,
          "indiscipline_total": 3,
          "pregnancy": 11,
          "pregnancy_total": 11,
          "truancy_male": 2491,
          "truancy_female": 2017,
          "truancy_total": 4508,
          "total_male": 2515,
          "total_female": 2040,
          "grand_total": 4555
        },
        {
          "region": "Tabora",
          "council": "Nzega",
          "death_male": 18,
          "death_female": 21,
          "death_total": 39,
          "indiscipline_male": 3,
          "indiscipline_female": 0,
          "indiscipline_total": 3,
          "pregnancy": 9,
          "pregnancy_total": 9,
          "truancy_male": 1350,
          "truancy_female": 978,
          "truancy_total": 2328,
          "total_male": 1371,
          "total_female": 1008,
          "grand_total": 2379
        },
        {
          "region": "Tabora",
          "council": "Nzega TC",
          "death_male": 2,
          "death_female": 0,
          "death_total": 2,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 74,
          "truancy_female": 52,
          "truancy_total": 126,
          "total_male": 76,
          "total_female": 53,
          "grand_total": 129
        },
        {
          "region": "Tabora",
          "council": "Sikonge",
          "death_male": 3,
          "death_female": 2,
          "death_total": 5,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 8,
          "pregnancy_total": 8,
          "truancy_male": 202,
          "truancy_female": 163,
          "truancy_total": 365,
          "total_male": 205,
          "total_female": 173,
          "grand_total": 378
        },
        {
          "region": "Tabora",
          "council": "Tabora MC",
          "death_male": 4,
          "death_female": 2,
          "death_total": 6,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 162,
          "truancy_female": 220,
          "truancy_total": 382,
          "total_male": 166,
          "total_female": 225,
          "grand_total": 391
        },
        {
          "region": "Tabora",
          "council": "Tabora/Uyui",
          "death_male": 29,
          "death_female": 16,
          "death_total": 45,
          "indiscipline_male": 4,
          "indiscipline_female": 3,
          "indiscipline_total": 7,
          "pregnancy": 11,
          "pregnancy_total": 11,
          "truancy_male": 1423,
          "truancy_female": 1210,
          "truancy_total": 2633,
          "total_male": 1456,
          "total_female": 1240,
          "grand_total": 2696
        },
        {
          "region": "Tabora",
          "council": "Urambo",
          "death_male": 14,
          "death_female": 12,
          "death_total": 26,
          "indiscipline_male": 10,
          "indiscipline_female": 5,
          "indiscipline_total": 15,
          "pregnancy": 7,
          "pregnancy_total": 7,
          "truancy_male": 679,
          "truancy_female": 490,
          "truancy_total": 1169,
          "total_male": 703,
          "total_female": 514,
          "grand_total": 1217
        },
        {
          "region": "Tanga",
          "council": "Bumbuli",
          "death_male": 0,
          "death_female": 2,
          "death_total": 2,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 14,
          "truancy_female": 24,
          "truancy_total": 38,
          "total_male": 14,
          "total_female": 27,
          "grand_total": 41
        },
        {
          "region": "Tanga",
          "council": "Handeni",
          "death_male": 10,
          "death_female": 13,
          "death_total": 23,
          "indiscipline_male": 5,
          "indiscipline_female": 6,
          "indiscipline_total": 11,
          "pregnancy": 18,
          "pregnancy_total": 18,
          "truancy_male": 457,
          "truancy_female": 319,
          "truancy_total": 776,
          "total_male": 472,
          "total_female": 356,
          "grand_total": 828
        },
        {
          "region": "Tanga",
          "council": "Handeni TC",
          "death_male": 4,
          "death_female": 3,
          "death_total": 7,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 28,
          "truancy_female": 22,
          "truancy_total": 50,
          "total_male": 32,
          "total_female": 27,
          "grand_total": 59
        },
        {
          "region": "Tanga",
          "council": "Kilindi",
          "death_male": 6,
          "death_female": 11,
          "death_total": 17,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 5,
          "pregnancy_total": 5,
          "truancy_male": 429,
          "truancy_female": 384,
          "truancy_total": 813,
          "total_male": 435,
          "total_female": 400,
          "grand_total": 835
        },
        {
          "region": "Tanga",
          "council": "Korogwe",
          "death_male": 6,
          "death_female": 1,
          "death_total": 7,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 3,
          "pregnancy_total": 3,
          "truancy_male": 185,
          "truancy_female": 100,
          "truancy_total": 285,
          "total_male": 191,
          "total_female": 104,
          "grand_total": 295
        },
        {
          "region": "Tanga",
          "council": "Korogwe TC",
          "death_male": 2,
          "death_female": 3,
          "death_total": 5,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 0,
          "truancy_female": 2,
          "truancy_total": 2,
          "total_male": 2,
          "total_female": 5,
          "grand_total": 7
        },
        {
          "region": "Tanga",
          "council": "Lushoto",
          "death_male": 30,
          "death_female": 17,
          "death_total": 47,
          "indiscipline_male": 5,
          "indiscipline_female": 0,
          "indiscipline_total": 5,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 972,
          "truancy_female": 681,
          "truancy_total": 1653,
          "total_male": 1007,
          "total_female": 698,
          "grand_total": 1705
        },
        {
          "region": "Tanga",
          "council": "Mkinga",
          "death_male": 3,
          "death_female": 3,
          "death_total": 6,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 0,
          "pregnancy_total": 0,
          "truancy_male": 124,
          "truancy_female": 116,
          "truancy_total": 240,
          "total_male": 127,
          "total_female": 119,
          "grand_total": 246
        },
        {
          "region": "Tanga",
          "council": "Muheza",
          "death_male": 4,
          "death_female": 0,
          "death_total": 4,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 1,
          "pregnancy_total": 1,
          "truancy_male": 34,
          "truancy_female": 25,
          "truancy_total": 59,
          "total_male": 38,
          "total_female": 26,
          "grand_total": 64
        },
        {
          "region": "Tanga",
          "council": "Pangani",
          "death_male": 2,
          "death_female": 1,
          "death_total": 3,
          "indiscipline_male": 0,
          "indiscipline_female": 0,
          "indiscipline_total": 0,
          "pregnancy": 2,
          "pregnancy_total": 2,
          "truancy_male": 19,
          "truancy_female": 16,
          "truancy_total": 35,
          "total_male": 21,
          "total_female": 19,
          "grand_total": 40
        },
        {
          "region": "Tanga",
          "council": "Tanga CC",
          "death_male": 6,
          "death_female": 4,
          "death_total": 10,
          "indiscipline_male": 2,
          "indiscipline_female": 0,
          "indiscipline_total": 2,
          "pregnancy": 9,
          "pregnancy_total": 9,
          "truancy_male": 72,
          "truancy_female": 40,
          "truancy_total": 112,
          "total_male": 80,
          "total_female": 53,
          "grand_total": 133
        },
        {
          "region": "Tanga",
          "council": "Tanga",
          "death_male": 1524,
          "death_female": 1070,
          "death_total": 2594,
          "indiscipline_male": 279,
          "indiscipline_female": 125,
          "indiscipline_total": 404,
          "pregnancy": 594,
          "pregnancy_total": 594,
          "truancy_male": 62007,
          "truancy_female": 52328,
          "truancy_total": 114335,
          "total_male": 63810,
          "total_female": 54117,
          "grand_total": 117927
        }
      ]
    
