export const data=[
    {
        "region": "REGION",
        "council": "COUNCIL",
        "death_male": "DEATH MALE",
        "death_female": "DEATH FEMALE",
        "death_total": "DEATH TOTAL",
        "indiscipline_male": "INDISCIPLINE MALE",
        "indiscipline_female": "INDISCIPLINE FEMALE",
        "indiscipline_total":"INDISCIPLINE TOTAL",
        "pregnancy_male":"PREGNANCY MALE",
        "pregnancy_female":"PREGNANCY FEMALE",
        "pregnancy_total":"PREGNANCY TOTAL",
        "truancy_male":"TRUANCY MALE",
        "truancy_female":"TRUANCY FEMALE",
        "truancy_total":"TRUANCY TOTAL",
        "total_male":"TOTAL MALE",
        "total_female":"TOTAL FEMALE",
        "grand_total":"GRAND TOTAL",
        "percent_of_enrollment":"PERCENTAGE OF TOTAL ENROLLMENT"

        
      },
    {
      "region": "Arusha",
      "council": "Arusha",
      "death_male": 8,
      "death_female": 4,
      "death_total": 12,
      "indiscipline_male": 6,
      "indiscipline_female": 4,
      "indiscipline_total": 10,
      "pregnancy_male": 0,
      "pregnancy_female": 20,
      "pregnancy_total": 20,
      "truancy_male": 300,
      "truancy_female": 241,
      "truancy_total": 541,
      "total_male": 314,
      "total_female": 269,
      "grand_total": 583,
      "percent_of_enrollment": 2.5
    },
    {
      "region": "Arusha",
      "council": "Arusha CC",
      "death_male": 3,
      "death_female": 2,
      "death_total": 5,
      "indiscipline_male": 5,
      "indiscipline_female": 2,
      "indiscipline_total": 7,
      "pregnancy_male": 0,
      "pregnancy_female": 5,
      "pregnancy_total": 5,
      "truancy_male": 129,
      "truancy_female": 122,
      "truancy_total": 251,
      "total_male": 137,
      "total_female": 131,
      "grand_total": 268,
      "%of Total Enrolment": 1
    },
    {
      "region": "Arusha",
      "council": "Karatu",
      "death_male": 0,
      "death_female": 2,
      "death_total": 2,
      "indiscipline_male": 2,
      "indiscipline_female": 2,
      "indiscipline_total": 4,
      "pregnancy_male": 0,
      "pregnancy_female": 24,
      "pregnancy_total": 24,
      "truancy_male": 146,
      "truancy_female": 157,
      "truancy_total": 303,
      "total_male": 148,
      "total_female": 185,
      "grand_total": 333,
      "%of Total Enrolment": 3.2
    },
    {
      "region": "Arusha",
      "council": "Longido",
      "death_male": 1,
      "death_female": 0,
      "death_total": 1,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 23,
      "pregnancy_total": 23,
      "truancy_male": 61,
      "truancy_female": 49,
      "truancy_total": 110,
      "total_male": 62,
      "total_female": 72,
      "grand_total": 134,
      "%of Total Enrolment": 2.3
    },
    {
      "region": "Arusha",
      "council": "Meru",
      "death_male": 4,
      "death_female": 1,
      "death_total": 5,
      "indiscipline_male": 32,
      "indiscipline_female": 10,
      "indiscipline_total": 42,
      "pregnancy_male": 0,
      "pregnancy_female": 26,
      "pregnancy_total": 26,
      "truancy_male": 187,
      "truancy_female": 106,
      "truancy_total": 293,
      "total_male": 223,
      "total_female": 143,
      "grand_total": 366,
      "%of Total Enrolment": 1.7
    },
    {
      "region": "Arusha",
      "council": "Monduli",
      "death_male": 3,
      "death_female": 0,
      "death_total": 3,
      "indiscipline_male": 1,
      "indiscipline_female": 0,
      "indiscipline_total": 1,
      "pregnancy_male": 0,
      "pregnancy_female": 24,
      "pregnancy_total": 24,
      "truancy_male": 124,
      "truancy_female": 53,
      "truancy_total": 177,
      "total_male": 128,
      "total_female": 77,
      "grand_total": 205,
      "%of Total Enrolment": 2.4
    },
    {
      "region": "Arusha",
      "council": "Ngorongoro",
      "death_male": 2,
      "death_female": 0,
      "death_total": 2,
      "indiscipline_male": 2,
      "indiscipline_female": 2,
      "indiscipline_total": 4,
      "pregnancy_male": 0,
      "pregnancy_female": 18,
      "pregnancy_total": 18,
      "truancy_male": 246,
      "truancy_female": 132,
      "truancy_total": 378,
      "total_male": 250,
      "total_female": 152,
      "grand_total": 402,
      "%of Total Enrolment": 7.4
    },
    {
      "region": "Dar-es-salaam",
      "council": "Ilala MC",
      "death_male": 22,
      "death_female": 10,
      "death_total": 32,
      "indiscipline_male": 22,
      "indiscipline_female": 12,
      "indiscipline_total": 34,
      "pregnancy_male": 0,
      "pregnancy_female": 29,
      "pregnancy_total": 29,
      "truancy_male": 161,
      "truancy_female": 109,
      "truancy_total": 270,
      "total_male": 205,
      "total_female": 160,
      "grand_total": 365,
      "%of Total Enrolment": 0.6
    },
    {
      "region": "Dar-es-salaam",
      "council": "Kigamboni MC",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 0,
      "pregnancy_total": 0,
      "truancy_male": 0,
      "truancy_female": 0,
      "truancy_total": 0,
      "total_male": 0,
      "total_female": 0,
      "grand_total": 0,
      "%of Total Enrolment": 0
    },
    {
      "region": "Dar-es-salaam",
      "council": "Kinondoni MC",
      "death_male": 25,
      "death_female": 16,
      "death_total": 41,
      "indiscipline_male": 51,
      "indiscipline_female": 22,
      "indiscipline_total": 73,
      "pregnancy_male": 0,
      "pregnancy_female": 21,
      "pregnancy_total": 21,
      "truancy_male": 277,
      "truancy_female": 210,
      "truancy_total": 487,
      "total_male": 353,
      "total_female": 269,
      "grand_total": 622,
      "%of Total Enrolment": 0.9
    },
    {
      "region": "Dar-es-salaam",
      "council": "Temeke MC",
      "death_male": 9,
      "death_female": 7,
      "death_total": 16,
      "indiscipline_male": 22,
      "indiscipline_female": 22,
      "indiscipline_total": 44,
      "pregnancy_male": 0,
      "pregnancy_female": 16,
      "pregnancy_total": 16,
      "truancy_male": 268,
      "truancy_female": 222,
      "truancy_total": 490,
      "total_male": 299,
      "total_female": 267,
      "grand_total": 566,
      "%of Total Enrolment": 0.7
    },
    {
      "region": "Dar-es-salaam",
      "council": "Ubungo MC",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 0,
      "pregnancy_total": 0,
      "truancy_male": 0,
      "truancy_female": 0,
      "truancy_total": 0,
      "total_male": 0,
      "total_female": 0,
      "grand_total": 0,
      "%of Total Enrolment": 0
    },
    {
      "region": "Dodoma",
      "council": "Bahi",
      "death_male": 1,
      "death_female": 4,
      "death_total": 5,
      "indiscipline_male": 2,
      "indiscipline_female": 1,
      "indiscipline_total": 3,
      "pregnancy_male": 0,
      "pregnancy_female": 26,
      "pregnancy_total": 26,
      "truancy_male": 191,
      "truancy_female": 142,
      "truancy_total": 333,
      "total_male": 194,
      "total_female": 173,
      "grand_total": 367,
      "%of Total Enrolment": 10.2
    },
    {
      "region": "Dodoma",
      "council": "Chamwino",
      "death_male": 2,
      "death_female": 1,
      "death_total": 3,
      "indiscipline_male": 1,
      "indiscipline_female": 1,
      "indiscipline_total": 2,
      "pregnancy_male": 0,
      "pregnancy_female": 42,
      "pregnancy_total": 42,
      "truancy_male": 143,
      "truancy_female": 153,
      "truancy_total": 296,
      "total_male": 146,
      "total_female": 197,
      "grand_total": 343,
      "%of Total Enrolment": 4.9
    },
    {
      "region": "Dodoma",
      "council": "Chemba",
      "death_male": 2,
      "death_female": 2,
      "death_total": 4,
      "indiscipline_male": 0,
      "indiscipline_female": 1,
      "indiscipline_total": 1,
      "pregnancy_male": 0,
      "pregnancy_female": 27,
      "pregnancy_total": 27,
      "truancy_male": 40,
      "truancy_female": 46,
      "truancy_total": 86,
      "total_male": 42,
      "total_female": 76,
      "grand_total": 118,
      "%of Total Enrolment": 2.6
    },
    {
      "region": "Dodoma",
      "council": "Dodoma MC",
      "death_male": 6,
      "death_female": 8,
      "death_total": 14,
      "indiscipline_male": 19,
      "indiscipline_female": 15,
      "indiscipline_total": 34,
      "pregnancy_male": 0,
      "pregnancy_female": 51,
      "pregnancy_total": 51,
      "truancy_male": 170,
      "truancy_female": 112,
      "truancy_total": 282,
      "total_male": 195,
      "total_female": 186,
      "grand_total": 381,
      "%of Total Enrolment": 1.7
    },
    {
      "region": "Dodoma",
      "council": "Kondoa",
      "death_male": 0,
      "death_female": 1,
      "death_total": 1,
      "indiscipline_male": 2,
      "indiscipline_female": 0,
      "indiscipline_total": 2,
      "pregnancy_male": 0,
      "pregnancy_female": 14,
      "pregnancy_total": 14,
      "truancy_male": 97,
      "truancy_female": 109,
      "truancy_total": 206,
      "total_male": 99,
      "total_female": 124,
      "grand_total": 223,
      "%of Total Enrolment": 4.5
    },
    {
      "region": "Dodoma",
      "council": "Kondoa TC",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 0,
      "pregnancy_total": 0,
      "truancy_male": 40,
      "truancy_female": 30,
      "truancy_total": 70,
      "total_male": 40,
      "total_female": 30,
      "grand_total": 70,
      "%of Total Enrolment": 1.6
    },
    {
      "region": "Dodoma",
      "council": "Kongwa",
      "death_male": 1,
      "death_female": 0,
      "death_total": 1,
      "indiscipline_male": 2,
      "indiscipline_female": 18,
      "indiscipline_total": 20,
      "pregnancy_male": 0,
      "pregnancy_female": 31,
      "pregnancy_total": 31,
      "truancy_male": 162,
      "truancy_female": 190,
      "truancy_total": 352,
      "total_male": 165,
      "total_female": 239,
      "grand_total": 404,
      "%of Total Enrolment": 4.7
    },
    {
      "region": "Dodoma",
      "council": "Mpwapwa",
      "death_male": 2,
      "death_female": 2,
      "death_total": 4,
      "indiscipline_male": 3,
      "indiscipline_female": 0,
      "indiscipline_total": 3,
      "pregnancy_male": 0,
      "pregnancy_female": 53,
      "pregnancy_total": 53,
      "truancy_male": 155,
      "truancy_female": 138,
      "truancy_total": 293,
      "total_male": 160,
      "total_female": 193,
      "grand_total": 353,
      "%of Total Enrolment": 4.7
    },
    {
      "region": "Geita",
      "council": "Bukombe",
      "death_male": 1,
      "death_female": 1,
      "death_total": 2,
      "indiscipline_male": 3,
      "indiscipline_female": 2,
      "indiscipline_total": 5,
      "pregnancy_male": 0,
      "pregnancy_female": 13,
      "pregnancy_total": 13,
      "truancy_male": 243,
      "truancy_female": 213,
      "truancy_total": 456,
      "total_male": 247,
      "total_female": 229,
      "grand_total": 476,
      "%of Total Enrolment": 6.1
    },
    {
      "region": "Geita",
      "council": "Chato",
      "death_male": 3,
      "death_female": 2,
      "death_total": 5,
      "indiscipline_male": 9,
      "indiscipline_female": 9,
      "indiscipline_total": 18,
      "pregnancy_male": 0,
      "pregnancy_female": 38,
      "pregnancy_total": 38,
      "truancy_male": 307,
      "truancy_female": 175,
      "truancy_total": 482,
      "total_male": 319,
      "total_female": 224,
      "grand_total": 543,
      "%of Total Enrolment": 4.8
    },
    {
      "region": "Geita",
      "council": "Geita",
      "death_male": 2,
      "death_female": 1,
      "death_total": 3,
      "indiscipline_male": 2,
      "indiscipline_female": 1,
      "indiscipline_total": 3,
      "pregnancy_male": 0,
      "pregnancy_female": 73,
      "pregnancy_total": 73,
      "truancy_male": 932,
      "truancy_female": 566,
      "truancy_total": 1498,
      "total_male": 936,
      "total_female": 641,
      "grand_total": 1577,
      "%of Total Enrolment": 9.1
    },
    {
      "region": "Geita",
      "council": "Geita TC",
      "death_male": 2,
      "death_female": 1,
      "death_total": 3,
      "indiscipline_male": 3,
      "indiscipline_female": 0,
      "indiscipline_total": 3,
      "pregnancy_male": 0,
      "pregnancy_female": 15,
      "pregnancy_total": 15,
      "truancy_male": 172,
      "truancy_female": 73,
      "truancy_total": 245,
      "total_male": 177,
      "total_female": 89,
      "grand_total": 266,
      "%of Total Enrolment": 2.5
    },
    {
      "region": "Geita",
      "council": "Mbogwe",
      "death_male": 3,
      "death_female": 0,
      "death_total": 3,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 28,
      "pregnancy_total": 28,
      "truancy_male": 753,
      "truancy_female": 611,
      "truancy_total": 1364,
      "total_male": 756,
      "total_female": 639,
      "grand_total": 1395,
      "%of Total Enrolment": 22.8
    },
    {
      "region": "Geita",
      "council": "Nyang'hwale",
      "death_male": 3,
      "death_female": 0,
      "death_total": 3,
      "indiscipline_male": 2,
      "indiscipline_female": 1,
      "indiscipline_total": 3,
      "pregnancy_male": 0,
      "pregnancy_female": 24,
      "pregnancy_total": 24,
      "truancy_male": 124,
      "truancy_female": 70,
      "truancy_total": 194,
      "total_male": 129,
      "total_female": 95,
      "grand_total": 224,
      "%of Total Enrolment": 5.1
    },
    {
      "region": "Iringa",
      "council": "Iringa",
      "death_male": 3,
      "death_female": 3,
      "death_total": 6,
      "indiscipline_male": 38,
      "indiscipline_female": 17,
      "indiscipline_total": 55,
      "pregnancy_male": 0,
      "pregnancy_female": 41,
      "pregnancy_total": 41,
      "truancy_male": 238,
      "truancy_female": 120,
      "truancy_total": 358,
      "total_male": 279,
      "total_female": 181,
      "grand_total": 460,
      "%of Total Enrolment": 2.7
    },
    {
      "region": "Iringa",
      "council": "Iringa MC",
      "death_male": 4,
      "death_female": 0,
      "death_total": 4,
      "indiscipline_male": 19,
      "indiscipline_female": 9,
      "indiscipline_total": 28,
      "pregnancy_male": 0,
      "pregnancy_female": 19,
      "pregnancy_total": 19,
      "truancy_male": 77,
      "truancy_female": 90,
      "truancy_total": 167,
      "total_male": 100,
      "total_female": 118,
      "grand_total": 218,
      "%of Total Enrolment": 1.7
    },
    {
      "region": "Iringa",
      "council": "Kilolo",
      "death_male": 3,
      "death_female": 5,
      "death_total": 8,
      "indiscipline_male": 6,
      "indiscipline_female": 6,
      "indiscipline_total": 12,
      "pregnancy_male": 0,
      "pregnancy_female": 53,
      "pregnancy_total": 53,
      "truancy_male": 122,
      "truancy_female": 74,
      "truancy_total": 196,
      "total_male": 131,
      "total_female": 138,
      "grand_total": 269,
      "%of Total Enrolment": 2.2
    },
    {
      "region": "Iringa",
      "council": "Mafinga TC",
      "death_male": 8,
      "death_female": 5,
      "death_total": 13,
      "indiscipline_male": 5,
      "indiscipline_female": 0,
      "indiscipline_total": 5,
      "pregnancy_male": 0,
      "pregnancy_female": 12,
      "pregnancy_total": 12,
      "truancy_male": 20,
      "truancy_female": 29,
      "truancy_total": 49,
      "total_male": 33,
      "total_female": 46,
      "grand_total": 79,
      "%of Total Enrolment": 1.1
    },
    {
      "region": "Iringa",
      "council": "Mufindi",
      "death_male": 3,
      "death_female": 4,
      "death_total": 7,
      "indiscipline_male": 7,
      "indiscipline_female": 6,
      "indiscipline_total": 13,
      "pregnancy_male": 0,
      "pregnancy_female": 63,
      "pregnancy_total": 63,
      "truancy_male": 285,
      "truancy_female": 227,
      "truancy_total": 512,
      "total_male": 295,
      "total_female": 300,
      "grand_total": 595,
      "%of Total Enrolment": 4.2
    },
    {
      "region": "Kagera",
      "council": "Biharamulo",
      "death_male": 2,
      "death_female": 1,
      "death_total": 3,
      "indiscipline_male": 3,
      "indiscipline_female": 1,
      "indiscipline_total": 4,
      "pregnancy_male": 0,
      "pregnancy_female": 9,
      "pregnancy_total": 9,
      "truancy_male": 453,
      "truancy_female": 484,
      "truancy_total": 937,
      "total_male": 458,
      "total_female": 495,
      "grand_total": 953,
      "%of Total Enrolment": 10.7
    },
    {
      "region": "Kagera",
      "council": "Bukoba",
      "death_male": 3,
      "death_female": 1,
      "death_total": 4,
      "indiscipline_male": 4,
      "indiscipline_female": 4,
      "indiscipline_total": 8,
      "pregnancy_male": 0,
      "pregnancy_female": 27,
      "pregnancy_total": 27,
      "truancy_male": 125,
      "truancy_female": 97,
      "truancy_total": 222,
      "total_male": 132,
      "total_female": 129,
      "grand_total": 261,
      "%of Total Enrolment": 2.2
    },
    {
      "region": "Kagera",
      "council": "Bukoba MC",
      "death_male": 2,
      "death_female": 2,
      "death_total": 4,
      "indiscipline_male": 15,
      "indiscipline_female": 3,
      "indiscipline_total": 18,
      "pregnancy_male": 0,
      "pregnancy_female": 13,
      "pregnancy_total": 13,
      "truancy_male": 28,
      "truancy_female": 27,
      "truancy_total": 55,
      "total_male": 45,
      "total_female": 45,
      "grand_total": 90,
      "%of Total Enrolment": 0.9
    },
    {
      "region": "Kagera",
      "council": "Karagwe",
      "death_male": 1,
      "death_female": 1,
      "death_total": 2,
      "indiscipline_male": 4,
      "indiscipline_female": 0,
      "indiscipline_total": 4,
      "pregnancy_male": 0,
      "pregnancy_female": 21,
      "pregnancy_total": 21,
      "truancy_male": 169,
      "truancy_female": 158,
      "truancy_total": 327,
      "total_male": 174,
      "total_female": 180,
      "grand_total": 354,
      "%of Total Enrolment": 3.4
    },
    {
      "region": "Kagera",
      "council": "Kyerwa",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 6,
      "indiscipline_female": 2,
      "indiscipline_total": 8,
      "pregnancy_male": 0,
      "pregnancy_female": 7,
      "pregnancy_total": 7,
      "truancy_male": 221,
      "truancy_female": 222,
      "truancy_total": 443,
      "total_male": 227,
      "total_female": 231,
      "grand_total": 458,
      "%of Total Enrolment": 6
    },
    {
      "region": "Kagera",
      "council": "Missenyi",
      "death_male": 2,
      "death_female": 1,
      "death_total": 3,
      "indiscipline_male": 5,
      "indiscipline_female": 3,
      "indiscipline_total": 8,
      "pregnancy_male": 0,
      "pregnancy_female": 13,
      "pregnancy_total": 13,
      "truancy_male": 135,
      "truancy_female": 106,
      "truancy_total": 241,
      "total_male": 142,
      "total_female": 123,
      "grand_total": 265,
      "%of Total Enrolment": 3.2
    },
    {
      "region": "Kagera",
      "council": "Muleba",
      "death_male": 3,
      "death_female": 2,
      "death_total": 5,
      "indiscipline_male": 4,
      "indiscipline_female": 11,
      "indiscipline_total": 15,
      "pregnancy_male": 0,
      "pregnancy_female": 55,
      "pregnancy_total": 55,
      "truancy_male": 458,
      "truancy_female": 405,
      "truancy_total": 863,
      "total_male": 465,
      "total_female": 473,
      "grand_total": 938,
      "%of Total Enrolment": 4.8
    },
    {
      "region": "Kagera",
      "council": "Ngara",
      "death_male": 1,
      "death_female": 2,
      "death_total": 3,
      "indiscipline_male": 1,
      "indiscipline_female": 1,
      "indiscipline_total": 2,
      "pregnancy_male": 0,
      "pregnancy_female": 14,
      "pregnancy_total": 14,
      "truancy_male": 259,
      "truancy_female": 227,
      "truancy_total": 486,
      "total_male": 261,
      "total_female": 244,
      "grand_total": 505,
      "%of Total Enrolment": 5.3
    },
    {
      "region": "Katavi",
      "council": "Mlele",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 7,
      "pregnancy_total": 7,
      "truancy_male": 38,
      "truancy_female": 23,
      "truancy_total": 61,
      "total_male": 38,
      "total_female": 30,
      "grand_total": 68,
      "%of Total Enrolment": 9.1
    },
    {
      "region": "Katavi",
      "council": "Mpanda",
      "death_male": 3,
      "death_female": 0,
      "death_total": 3,
      "indiscipline_male": 1,
      "indiscipline_female": 0,
      "indiscipline_total": 1,
      "pregnancy_male": 0,
      "pregnancy_female": 16,
      "pregnancy_total": 16,
      "truancy_male": 218,
      "truancy_female": 167,
      "truancy_total": 385,
      "total_male": 222,
      "total_female": 183,
      "grand_total": 405,
      "%of Total Enrolment": 12.4
    },
    {
      "region": "Katavi",
      "council": "Mpanda MC",
      "death_male": 3,
      "death_female": 1,
      "death_total": 4,
      "indiscipline_male": 2,
      "indiscipline_female": 1,
      "indiscipline_total": 3,
      "pregnancy_male": 0,
      "pregnancy_female": 25,
      "pregnancy_total": 25,
      "truancy_male": 63,
      "truancy_female": 48,
      "truancy_total": 111,
      "total_male": 68,
      "total_female": 75,
      "grand_total": 143,
      "%of Total Enrolment": 2.5
    },
    {
      "region": "Katavi",
      "council": "Mpimbwe",
      "death_male": 1,
      "death_female": 0,
      "death_total": 1,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 12,
      "pregnancy_total": 12,
      "truancy_male": 22,
      "truancy_female": 12,
      "truancy_total": 34,
      "total_male": 23,
      "total_female": 24,
      "grand_total": 47,
      "%of Total Enrolment": 2.9
    },
    {
      "region": "Katavi",
      "council": "Nsimbo",
      "death_male": 2,
      "death_female": 1,
      "death_total": 3,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 13,
      "pregnancy_total": 13,
      "truancy_male": 98,
      "truancy_female": 79,
      "truancy_total": 177,
      "total_male": 100,
      "total_female": 93,
      "grand_total": 193,
      "%of Total Enrolment": 5.6
    },
    {
      "region": "Kigoma",
      "council": "Buhigwe",
      "death_male": 3,
      "death_female": 0,
      "death_total": 3,
      "indiscipline_male": 5,
      "indiscipline_female": 0,
      "indiscipline_total": 5,
      "pregnancy_male": 0,
      "pregnancy_female": 16,
      "pregnancy_total": 16,
      "truancy_male": 158,
      "truancy_female": 77,
      "truancy_total": 235,
      "total_male": 166,
      "total_female": 93,
      "grand_total": 259,
      "%of Total Enrolment": 3.9
    },
    {
      "region": "Kigoma",
      "council": "Kakonko",
      "death_male": 1,
      "death_female": 1,
      "death_total": 2,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 0,
      "pregnancy_total": 0,
      "truancy_male": 118,
      "truancy_female": 65,
      "truancy_total": 183,
      "total_male": 119,
      "total_female": 66,
      "grand_total": 185,
      "%of Total Enrolment": 4.8
    },
    {
      "region": "Kigoma",
      "council": "Kasulu",
      "death_male": 2,
      "death_female": 1,
      "death_total": 3,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 5,
      "pregnancy_total": 5,
      "truancy_male": 75,
      "truancy_female": 47,
      "truancy_total": 122,
      "total_male": 77,
      "total_female": 53,
      "grand_total": 130,
      "%of Total Enrolment": 2.8
    },
    {
      "region": "Kigoma",
      "council": "Kasulu TC",
      "death_male": 1,
      "death_female": 1,
      "death_total": 2,
      "indiscipline_male": 12,
      "indiscipline_female": 10,
      "indiscipline_total": 22,
      "pregnancy_male": 0,
      "pregnancy_female": 11,
      "pregnancy_total": 11,
      "truancy_male": 16,
      "truancy_female": 22,
      "truancy_total": 38,
      "total_male": 29,
      "total_female": 44,
      "grand_total": 73,
      "%of Total Enrolment": 0.9
    },
    {
      "region": "Kigoma",
      "council": "Kibondo",
      "death_male": 3,
      "death_female": 1,
      "death_total": 4,
      "indiscipline_male": 1,
      "indiscipline_female": 5,
      "indiscipline_total": 6,
      "pregnancy_male": 0,
      "pregnancy_female": 12,
      "pregnancy_total": 12,
      "truancy_male": 212,
      "truancy_female": 154,
      "truancy_total": 366,
      "total_male": 216,
      "total_female": 172,
      "grand_total": 388,
      "%of Total Enrolment": 4.7
    },
    {
      "region": "Kigoma",
      "council": "Kigoma",
      "death_male": 0,
      "death_female": 1,
      "death_total": 1,
      "indiscipline_male": 3,
      "indiscipline_female": 6,
      "indiscipline_total": 9,
      "pregnancy_male": 0,
      "pregnancy_female": 8,
      "pregnancy_total": 8,
      "truancy_male": 70,
      "truancy_female": 24,
      "truancy_total": 94,
      "total_male": 73,
      "total_female": 39,
      "grand_total": 112,
      "%of Total Enrolment": 1.6
    },
    {
      "region": "Kigoma",
      "council": "Kigoma/Ujiji MC",
      "death_male": 10,
      "death_female": 13,
      "death_total": 23,
      "indiscipline_male": 3,
      "indiscipline_female": 0,
      "indiscipline_total": 3,
      "pregnancy_male": 0,
      "pregnancy_female": 22,
      "pregnancy_total": 22,
      "truancy_male": 158,
      "truancy_female": 81,
      "truancy_total": 239,
      "total_male": 171,
      "total_female": 116,
      "grand_total": 287,
      "%of Total Enrolment": 2.6
    },
    {
      "region": "Kigoma",
      "council": "Uvinza",
      "death_male": 1,
      "death_female": 0,
      "death_total": 1,
      "indiscipline_male": 6,
      "indiscipline_female": 1,
      "indiscipline_total": 7,
      "pregnancy_male": 0,
      "pregnancy_female": 8,
      "pregnancy_total": 8,
      "truancy_male": 194,
      "truancy_female": 106,
      "truancy_total": 300,
      "total_male": 201,
      "total_female": 115,
      "grand_total": 316,
      "%of Total Enrolment": 5.9
    },
    {
      "region": "Kilimanjaro",
      "council": "Hai",
      "death_male": 2,
      "death_female": 2,
      "death_total": 4,
      "indiscipline_male": 9,
      "indiscipline_female": 9,
      "indiscipline_total": 18,
      "pregnancy_male": 0,
      "pregnancy_female": 46,
      "pregnancy_total": 46,
      "truancy_male": 117,
      "truancy_female": 95,
      "truancy_total": 212,
      "total_male": 128,
      "total_female": 152,
      "grand_total": 280,
      "%of Total Enrolment": 1.9
    },
    {
      "region": "Kilimanjaro",
      "council": "Moshi",
      "death_male": 2,
      "death_female": 4,
      "death_total": 6,
      "indiscipline_male": 44,
      "indiscipline_female": 3,
      "indiscipline_total": 47,
      "pregnancy_male": 0,
      "pregnancy_female": 87,
      "pregnancy_total": 87,
      "truancy_male": 209,
      "truancy_female": 176,
      "truancy_total": 385,
      "total_male": 255,
      "total_female": 270,
      "grand_total": 525,
      "%of Total Enrolment": 1.4
    },
    {
      "region": "Kilimanjaro",
      "council": "Moshi MC",
      "death_male": 1,
      "death_female": 0,
      "death_total": 1,
      "indiscipline_male": 7,
      "indiscipline_female": 3,
      "indiscipline_total": 10,
      "pregnancy_male": 0,
      "pregnancy_female": 22,
      "pregnancy_total": 22,
      "truancy_male": 69,
      "truancy_female": 36,
      "truancy_total": 105,
      "total_male": 77,
      "total_female": 61,
      "grand_total": 138,
      "%of Total Enrolment": 0.8
    },
    {
      "region": "Kilimanjaro",
      "council": "Mwanga",
      "death_male": 1,
      "death_female": 0,
      "death_total": 1,
      "indiscipline_male": 4,
      "indiscipline_female": 0,
      "indiscipline_total": 4,
      "pregnancy_male": 0,
      "pregnancy_female": 44,
      "pregnancy_total": 44,
      "truancy_male": 103,
      "truancy_female": 64,
      "truancy_total": 167,
      "total_male": 108,
      "total_female": 108,
      "grand_total": 216,
      "%of Total Enrolment": 1.3
    },
    {
      "region": "Kilimanjaro",
      "council": "Rombo",
      "death_male": 16,
      "death_female": 6,
      "death_total": 22,
      "indiscipline_male": 27,
      "indiscipline_female": 18,
      "indiscipline_total": 45,
      "pregnancy_male": 0,
      "pregnancy_female": 74,
      "pregnancy_total": 74,
      "truancy_male": 222,
      "truancy_female": 151,
      "truancy_total": 373,
      "total_male": 265,
      "total_female": 249,
      "grand_total": 514,
      "%of Total Enrolment": 2.6
    },
    {
      "region": "Kilimanjaro",
      "council": "Same",
      "death_male": 1,
      "death_female": 1,
      "death_total": 2,
      "indiscipline_male": 13,
      "indiscipline_female": 9,
      "indiscipline_total": 22,
      "pregnancy_male": 0,
      "pregnancy_female": 53,
      "pregnancy_total": 53,
      "truancy_male": 322,
      "truancy_female": 206,
      "truancy_total": 528,
      "total_male": 336,
      "total_female": 269,
      "grand_total": 605,
      "%of Total Enrolment": 2.8
    },
    {
      "region": "Kilimanjaro",
      "council": "Siha",
      "death_male": 1,
      "death_female": 2,
      "death_total": 3,
      "indiscipline_male": 4,
      "indiscipline_female": 0,
      "indiscipline_total": 4,
      "pregnancy_male": 0,
      "pregnancy_female": 9,
      "pregnancy_total": 9,
      "truancy_male": 65,
      "truancy_female": 39,
      "truancy_total": 104,
      "total_male": 70,
      "total_female": 50,
      "grand_total": 120,
      "%of Total Enrolment": 1.8
    },
    {
      "region": "Lindi",
      "council": "Kilwa",
      "death_male": 1,
      "death_female": 2,
      "death_total": 3,
      "indiscipline_male": 8,
      "indiscipline_female": 2,
      "indiscipline_total": 10,
      "pregnancy_male": 0,
      "pregnancy_female": 30,
      "pregnancy_total": 30,
      "truancy_male": 178,
      "truancy_female": 105,
      "truancy_total": 283,
      "total_male": 187,
      "total_female": 139,
      "grand_total": 326,
      "%of Total Enrolment": 5.9
    },
    {
      "region": "Lindi",
      "council": "Lindi",
      "death_male": 3,
      "death_female": 1,
      "death_total": 4,
      "indiscipline_male": 15,
      "indiscipline_female": 4,
      "indiscipline_total": 19,
      "pregnancy_male": 0,
      "pregnancy_female": 16,
      "pregnancy_total": 16,
      "truancy_male": 92,
      "truancy_female": 61,
      "truancy_total": 153,
      "total_male": 110,
      "total_female": 82,
      "grand_total": 192,
      "%of Total Enrolment": 3.6
    },
    {
      "region": "Lindi",
      "council": "Lindi MC",
      "death_male": 0,
      "death_female": 1,
      "death_total": 1,
      "indiscipline_male": 0,
      "indiscipline_female": 1,
      "indiscipline_total": 1,
      "pregnancy_male": 0,
      "pregnancy_female": 12,
      "pregnancy_total": 12,
      "truancy_male": 46,
      "truancy_female": 28,
      "truancy_total": 74,
      "total_male": 46,
      "total_female": 42,
      "grand_total": 88,
      "%of Total Enrolment": 2.5
    },
    {
      "region": "Lindi",
      "council": "Liwale",
      "death_male": 0,
      "death_female": 1,
      "death_total": 1,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 3,
      "pregnancy_total": 3,
      "truancy_male": 134,
      "truancy_female": 99,
      "truancy_total": 233,
      "total_male": 134,
      "total_female": 103,
      "grand_total": 237,
      "%of Total Enrolment": 5.6
    },
    {
      "region": "Lindi",
      "council": "Nachingwea",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 1,
      "indiscipline_female": 1,
      "indiscipline_total": 2,
      "pregnancy_male": 0,
      "pregnancy_female": 6,
      "pregnancy_total": 6,
      "truancy_male": 139,
      "truancy_female": 87,
      "truancy_total": 226,
      "total_male": 140,
      "total_female": 94,
      "grand_total": 234,
      "%of Total Enrolment": 4.2
    },
    {
      "region": "Lindi",
      "council": "Ruangwa",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 3,
      "indiscipline_female": 0,
      "indiscipline_total": 3,
      "pregnancy_male": 0,
      "pregnancy_female": 4,
      "pregnancy_total": 4,
      "truancy_male": 59,
      "truancy_female": 45,
      "truancy_total": 104,
      "total_male": 62,
      "total_female": 49,
      "grand_total": 111,
      "%of Total Enrolment": 3.4
    },
    {
      "region": "Manyara",
      "council": "Babati",
      "death_male": 1,
      "death_female": 0,
      "death_total": 1,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 5,
      "pregnancy_total": 5,
      "truancy_male": 219,
      "truancy_female": 163,
      "truancy_total": 382,
      "total_male": 220,
      "total_female": 168,
      "grand_total": 388,
      "%of Total Enrolment": 3.2
    },
    {
      "region": "Manyara",
      "council": "Babati TC",
      "death_male": 0,
      "death_female": 1,
      "death_total": 1,
      "indiscipline_male": 2,
      "indiscipline_female": 6,
      "indiscipline_total": 8,
      "pregnancy_male": 0,
      "pregnancy_female": 6,
      "pregnancy_total": 6,
      "truancy_male": 35,
      "truancy_female": 20,
      "truancy_total": 55,
      "total_male": 37,
      "total_female": 33,
      "grand_total": 70,
      "%of Total Enrolment": 1
    },
    {
      "region": "Manyara",
      "council": "Hanang",
      "death_male": 1,
      "death_female": 1,
      "death_total": 2,
      "indiscipline_male": 0,
      "indiscipline_female": 2,
      "indiscipline_total": 2,
      "pregnancy_male": 0,
      "pregnancy_female": 10,
      "pregnancy_total": 10,
      "truancy_male": 189,
      "truancy_female": 161,
      "truancy_total": 350,
      "total_male": 190,
      "total_female": 174,
      "grand_total": 364,
      "%of Total Enrolment": 4.7
    },
    {
      "region": "Manyara",
      "council": "Kiteto",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 60,
      "pregnancy_total": 60,
      "truancy_male": 47,
      "truancy_female": 84,
      "truancy_total": 131,
      "total_male": 47,
      "total_female": 144,
      "grand_total": 191,
      "%of Total Enrolment": 4.2
    },
    {
      "region": "Manyara",
      "council": "Mbulu",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 0,
      "pregnancy_total": 0,
      "truancy_male": 196,
      "truancy_female": 262,
      "truancy_total": 458,
      "total_male": 196,
      "total_female": 262,
      "grand_total": 458,
      "%of Total Enrolment": 7.8
    },
    {
      "region": "Manyara",
      "council": "Mbulu TC",
      "death_male": 1,
      "death_female": 0,
      "death_total": 1,
      "indiscipline_male": 2,
      "indiscipline_female": 0,
      "indiscipline_total": 2,
      "pregnancy_male": 0,
      "pregnancy_female": 2,
      "pregnancy_total": 2,
      "truancy_male": 160,
      "truancy_female": 148,
      "truancy_total": 308,
      "total_male": 163,
      "total_female": 150,
      "grand_total": 313,
      "%of Total Enrolment": 4.8
    },
    {
      "region": "Manyara",
      "council": "Simanjiro",
      "death_male": 1,
      "death_female": 1,
      "death_total": 2,
      "indiscipline_male": 6,
      "indiscipline_female": 8,
      "indiscipline_total": 14,
      "pregnancy_male": 0,
      "pregnancy_female": 13,
      "pregnancy_total": 13,
      "truancy_male": 79,
      "truancy_female": 31,
      "truancy_total": 110,
      "total_male": 86,
      "total_female": 53,
      "grand_total": 139,
      "%of Total Enrolment": 3.2
    },
    {
      "region": "Mara",
      "council": "Bunda",
      "death_male": 5,
      "death_female": 2,
      "death_total": 7,
      "indiscipline_male": 8,
      "indiscipline_female": 9,
      "indiscipline_total": 17,
      "pregnancy_male": 0,
      "pregnancy_female": 37,
      "pregnancy_total": 37,
      "truancy_male": 195,
      "truancy_female": 121,
      "truancy_total": 316,
      "total_male": 208,
      "total_female": 169,
      "grand_total": 377,
      "%of Total Enrolment": 4.6
    },
    {
      "region": "Mara",
      "council": "Bunda TC",
      "death_male": 1,
      "death_female": 0,
      "death_total": 1,
      "indiscipline_male": 1,
      "indiscipline_female": 0,
      "indiscipline_total": 1,
      "pregnancy_male": 0,
      "pregnancy_female": 14,
      "pregnancy_total": 14,
      "truancy_male": 138,
      "truancy_female": 108,
      "truancy_total": 246,
      "total_male": 140,
      "total_female": 122,
      "grand_total": 262,
      "%of Total Enrolment": 3.9
    },
    {
      "region": "Mara",
      "council": "Butiama",
      "death_male": 1,
      "death_female": 1,
      "death_total": 2,
      "indiscipline_male": 6,
      "indiscipline_female": 0,
      "indiscipline_total": 6,
      "pregnancy_male": 0,
      "pregnancy_female": 34,
      "pregnancy_total": 34,
      "truancy_male": 180,
      "truancy_female": 84,
      "truancy_total": 264,
      "total_male": 187,
      "total_female": 119,
      "grand_total": 306,
      "%of Total Enrolment": 3.4
    },
    {
      "region": "Mara",
      "council": "Musoma",
      "death_male": 4,
      "death_female": 0,
      "death_total": 4,
      "indiscipline_male": 5,
      "indiscipline_female": 0,
      "indiscipline_total": 5,
      "pregnancy_male": 0,
      "pregnancy_female": 24,
      "pregnancy_total": 24,
      "truancy_male": 229,
      "truancy_female": 135,
      "truancy_total": 364,
      "total_male": 238,
      "total_female": 159,
      "grand_total": 397,
      "%of Total Enrolment": 5.6
    },
    {
      "region": "Mara",
      "council": "Musoma MC",
      "death_male": 2,
      "death_female": 0,
      "death_total": 2,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 11,
      "pregnancy_total": 11,
      "truancy_male": 126,
      "truancy_female": 65,
      "truancy_total": 191,
      "total_male": 128,
      "total_female": 76,
      "grand_total": 204,
      "%of Total Enrolment": 1.7
    },
    {
      "region": "Mara",
      "council": "Rorya",
      "death_male": 11,
      "death_female": 4,
      "death_total": 15,
      "indiscipline_male": 7,
      "indiscipline_female": 0,
      "indiscipline_total": 7,
      "pregnancy_male": 0,
      "pregnancy_female": 66,
      "pregnancy_total": 66,
      "truancy_male": 159,
      "truancy_female": 100,
      "truancy_total": 259,
      "total_male": 177,
      "total_female": 170,
      "grand_total": 347,
      "%of Total Enrolment": 3.4
    },
    {
      "region": "Mara",
      "council": "Serengeti",
      "death_male": 4,
      "death_female": 3,
      "death_total": 7,
      "indiscipline_male": 9,
      "indiscipline_female": 2,
      "indiscipline_total": 11,
      "pregnancy_male": 0,
      "pregnancy_female": 26,
      "pregnancy_total": 26,
      "truancy_male": 199,
      "truancy_female": 130,
      "truancy_total": 329,
      "total_male": 212,
      "total_female": 161,
      "grand_total": 373,
      "%of Total Enrolment": 4
    },
    {
      "region": "Mara",
      "council": "Tarime",
      "death_male": 5,
      "death_female": 2,
      "death_total": 7,
      "indiscipline_male": 5,
      "indiscipline_female": 0,
      "indiscipline_total": 5,
      "pregnancy_male": 0,
      "pregnancy_female": 22,
      "pregnancy_total": 22,
      "truancy_male": 199,
      "truancy_female": 143,
      "truancy_total": 342,
      "total_male": 209,
      "total_female": 167,
      "grand_total": 376,
      "%of Total Enrolment": 4.4
    },
    {
      "region": "Mara",
      "council": "Tarime TC",
      "death_male": 1,
      "death_female": 1,
      "death_total": 2,
      "indiscipline_male": 4,
      "indiscipline_female": 0,
      "indiscipline_total": 4,
      "pregnancy_male": 0,
      "pregnancy_female": 5,
      "pregnancy_total": 5,
      "truancy_male": 59,
      "truancy_female": 38,
      "truancy_total": 97,
      "total_male": 64,
      "total_female": 44,
      "grand_total": 108,
      "%of Total Enrolment": 2
    },
    {
      "region": "Mbeya",
      "council": "Busokelo",
      "death_male": 0,
      "death_female": 2,
      "death_total": 2,
      "indiscipline_male": 3,
      "indiscipline_female": 2,
      "indiscipline_total": 5,
      "pregnancy_male": 0,
      "pregnancy_female": 50,
      "pregnancy_total": 50,
      "truancy_male": 115,
      "truancy_female": 70,
      "truancy_total": 185,
      "total_male": 118,
      "total_female": 124,
      "grand_total": 242,
      "%of Total Enrolment": 3.2
    },
    {
      "region": "Mbeya",
      "council": "Chunya",
      "death_male": 6,
      "death_female": 1,
      "death_total": 7,
      "indiscipline_male": 5,
      "indiscipline_female": 3,
      "indiscipline_total": 8,
      "pregnancy_male": 0,
      "pregnancy_female": 37,
      "pregnancy_total": 37,
      "truancy_male": 210,
      "truancy_female": 178,
      "truancy_total": 388,
      "total_male": 221,
      "total_female": 219,
      "grand_total": 440,
      "%of Total Enrolment": 6.7
    },
    {
      "region": "Mbeya",
      "council": "Kyela",
      "death_male": 3,
      "death_female": 3,
      "death_total": 6,
      "indiscipline_male": 9,
      "indiscipline_female": 1,
      "indiscipline_total": 10,
      "pregnancy_male": 0,
      "pregnancy_female": 51,
      "pregnancy_total": 51,
      "truancy_male": 172,
      "truancy_female": 147,
      "truancy_total": 319,
      "total_male": 184,
      "total_female": 202,
      "grand_total": 386,
      "%of Total Enrolment": 3
    },
    {
      "region": "Mbeya",
      "council": "Mbarali",
      "death_male": 1,
      "death_female": 0,
      "death_total": 1,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 31,
      "pregnancy_total": 31,
      "truancy_male": 134,
      "truancy_female": 134,
      "truancy_total": 268,
      "total_male": 135,
      "total_female": 165,
      "grand_total": 300,
      "%of Total Enrolment": 3
    },
    {
      "region": "Mbeya",
      "council": "Mbeya",
      "death_male": 5,
      "death_female": 2,
      "death_total": 7,
      "indiscipline_male": 12,
      "indiscipline_female": 2,
      "indiscipline_total": 14,
      "pregnancy_male": 0,
      "pregnancy_female": 67,
      "pregnancy_total": 67,
      "truancy_male": 113,
      "truancy_female": 108,
      "truancy_total": 221,
      "total_male": 130,
      "total_female": 179,
      "grand_total": 309,
      "%of Total Enrolment": 1.7
    },
    {
      "region": "Mbeya",
      "council": "Mbeya CC",
      "death_male": 6,
      "death_female": 2,
      "death_total": 8,
      "indiscipline_male": 12,
      "indiscipline_female": 3,
      "indiscipline_total": 15,
      "pregnancy_male": 0,
      "pregnancy_female": 76,
      "pregnancy_total": 76,
      "truancy_male": 171,
      "truancy_female": 175,
      "truancy_total": 346,
      "total_male": 189,
      "total_female": 256,
      "grand_total": 445,
      "%of Total Enrolment": 1.3
    },
    {
      "region": "Mbeya",
      "council": "Rungwe",
      "death_male": 1,
      "death_female": 7,
      "death_total": 8,
      "indiscipline_male": 32,
      "indiscipline_female": 5,
      "indiscipline_total": 37,
      "pregnancy_male": 0,
      "pregnancy_female": 51,
      "pregnancy_total": 51,
      "truancy_male": 205,
      "truancy_female": 169,
      "truancy_total": 374,
      "total_male": 238,
      "total_female": 232,
      "grand_total": 470,
      "%of Total Enrolment": 2.6
    },
    {
      "region": "Morogoro",
      "council": "Gairo",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 1,
      "indiscipline_female": 1,
      "indiscipline_total": 2,
      "pregnancy_male": 0,
      "pregnancy_female": 28,
      "pregnancy_total": 28,
      "truancy_male": 91,
      "truancy_female": 106,
      "truancy_total": 197,
      "total_male": 92,
      "total_female": 135,
      "grand_total": 227,
      "%of Total Enrolment": 6.6
    },
    {
      "region": "Morogoro",
      "council": "Ifakara TC",
      "death_male": 1,
      "death_female": 1,
      "death_total": 2,
      "indiscipline_male": 4,
      "indiscipline_female": 1,
      "indiscipline_total": 5,
      "pregnancy_male": 0,
      "pregnancy_female": 15,
      "pregnancy_total": 15,
      "truancy_male": 115,
      "truancy_female": 100,
      "truancy_total": 215,
      "total_male": 120,
      "total_female": 117,
      "grand_total": 237,
      "%of Total Enrolment": 3.6
    },
    {
      "region": "Morogoro",
      "council": "Kilombero",
      "death_male": 2,
      "death_female": 3,
      "death_total": 5,
      "indiscipline_male": 6,
      "indiscipline_female": 4,
      "indiscipline_total": 10,
      "pregnancy_male": 0,
      "pregnancy_female": 29,
      "pregnancy_total": 29,
      "truancy_male": 90,
      "truancy_female": 62,
      "truancy_total": 152,
      "total_male": 98,
      "total_female": 98,
      "grand_total": 196,
      "%of Total Enrolment": 1.8
    },
    {
      "region": "Morogoro",
      "council": "Kilosa",
      "death_male": 2,
      "death_female": 2,
      "death_total": 4,
      "indiscipline_male": 11,
      "indiscipline_female": 15,
      "indiscipline_total": 26,
      "pregnancy_male": 0,
      "pregnancy_female": 48,
      "pregnancy_total": 48,
      "truancy_male": 165,
      "truancy_female": 138,
      "truancy_total": 303,
      "total_male": 178,
      "total_female": 203,
      "grand_total": 381,
      "%of Total Enrolment": 2.7
    },
    {
      "region": "Morogoro",
      "council": "Malinyi",
      "death_male": 0,
      "death_female": 1,
      "death_total": 1,
      "indiscipline_male": 6,
      "indiscipline_female": 4,
      "indiscipline_total": 10,
      "pregnancy_male": 0,
      "pregnancy_female": 14,
      "pregnancy_total": 14,
      "truancy_male": 38,
      "truancy_female": 14,
      "truancy_total": 52,
      "total_male": 44,
      "total_female": 33,
      "grand_total": 77,
      "%of Total Enrolment": 1.9
    },
    {
      "region": "Morogoro",
      "council": "Morogoro",
      "death_male": 7,
      "death_female": 9,
      "death_total": 16,
      "indiscipline_male": 3,
      "indiscipline_female": 0,
      "indiscipline_total": 3,
      "pregnancy_male": 0,
      "pregnancy_female": 27,
      "pregnancy_total": 27,
      "truancy_male": 139,
      "truancy_female": 87,
      "truancy_total": 226,
      "total_male": 149,
      "total_female": 123,
      "grand_total": 272,
      "%of Total Enrolment": 3.6
    },
    {
      "region": "Morogoro",
      "council": "Morogoro MC",
      "death_male": 3,
      "death_female": 2,
      "death_total": 5,
      "indiscipline_male": 47,
      "indiscipline_female": 14,
      "indiscipline_total": 61,
      "pregnancy_male": 0,
      "pregnancy_female": 16,
      "pregnancy_total": 16,
      "truancy_male": 96,
      "truancy_female": 100,
      "truancy_total": 196,
      "total_male": 146,
      "total_female": 132,
      "grand_total": 278,
      "%of Total Enrolment": 1.2
    },
    {
      "region": "Morogoro",
      "council": "Mvomero",
      "death_male": 3,
      "death_female": 4,
      "death_total": 7,
      "indiscipline_male": 33,
      "indiscipline_female": 41,
      "indiscipline_total": 74,
      "pregnancy_male": 0,
      "pregnancy_female": 38,
      "pregnancy_total": 38,
      "truancy_male": 137,
      "truancy_female": 139,
      "truancy_total": 276,
      "total_male": 173,
      "total_female": 222,
      "grand_total": 395,
      "%of Total Enrolment": 3.9
    },
    {
      "region": "Morogoro",
      "council": "Ulanga",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 5,
      "indiscipline_female": 6,
      "indiscipline_total": 11,
      "pregnancy_male": 0,
      "pregnancy_female": 14,
      "pregnancy_total": 14,
      "truancy_male": 70,
      "truancy_female": 46,
      "truancy_total": 116,
      "total_male": 75,
      "total_female": 66,
      "grand_total": 141,
      "%of Total Enrolment": 2.3
    },
    {
      "region": "Mtwara",
      "council": "Masasi",
      "death_male": 0,
      "death_female": 1,
      "death_total": 1,
      "indiscipline_male": 21,
      "indiscipline_female": 3,
      "indiscipline_total": 24,
      "pregnancy_male": 0,
      "pregnancy_female": 26,
      "pregnancy_total": 26,
      "truancy_male": 200,
      "truancy_female": 162,
      "truancy_total": 362,
      "total_male": 221,
      "total_female": 192,
      "grand_total": 413,
      "%of Total Enrolment": 5.1
    },
    {
      "region": "Mtwara",
      "council": "Masasi TC",
      "death_male": 8,
      "death_female": 7,
      "death_total": 15,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 10,
      "pregnancy_total": 10,
      "truancy_male": 156,
      "truancy_female": 126,
      "truancy_total": 282,
      "total_male": 164,
      "total_female": 143,
      "grand_total": 307,
      "%of Total Enrolment": 8.2
    },
    {
      "region": "Mtwara",
      "council": "Mtwara",
      "death_male": 2,
      "death_female": 1,
      "death_total": 3,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 12,
      "pregnancy_total": 12,
      "truancy_male": 154,
      "truancy_female": 131,
      "truancy_total": 285,
      "total_male": 156,
      "total_female": 144,
      "grand_total": 300,
      "%of Total Enrolment": 7.7
    },
    {
      "region": "Mtwara",
      "council": "Mtwara Mikindani MC",
      "death_male": 4,
      "death_female": 2,
      "death_total": 6,
      "indiscipline_male": 4,
      "indiscipline_female": 1,
      "indiscipline_total": 5,
      "pregnancy_male": 0,
      "pregnancy_female": 15,
      "pregnancy_total": 15,
      "truancy_male": 78,
      "truancy_female": 40,
      "truancy_total": 118,
      "total_male": 86,
      "total_female": 58,
      "grand_total": 144,
      "%of Total Enrolment": 1.7
    },
    {
      "region": "Mtwara",
      "council": "Nanyamba",
      "death_male": 3,
      "death_female": 0,
      "death_total": 3,
      "indiscipline_male": 1,
      "indiscipline_female": 1,
      "indiscipline_total": 2,
      "pregnancy_male": 0,
      "pregnancy_female": 30,
      "pregnancy_total": 30,
      "truancy_male": 154,
      "truancy_female": 159,
      "truancy_total": 313,
      "total_male": 158,
      "total_female": 190,
      "grand_total": 348,
      "%of Total Enrolment": 9.2
    },
    {
      "region": "Mtwara",
      "council": "Nanyumbu",
      "death_male": 0,
      "death_female": 2,
      "death_total": 2,
      "indiscipline_male": 1,
      "indiscipline_female": 0,
      "indiscipline_total": 1,
      "pregnancy_male": 0,
      "pregnancy_female": 14,
      "pregnancy_total": 14,
      "truancy_male": 182,
      "truancy_female": 175,
      "truancy_total": 357,
      "total_male": 183,
      "total_female": 191,
      "grand_total": 374,
      "%of Total Enrolment": 12.3
    },
    {
      "region": "Mtwara",
      "council": "Newala",
      "death_male": 1,
      "death_female": 0,
      "death_total": 1,
      "indiscipline_male": 2,
      "indiscipline_female": 2,
      "indiscipline_total": 4,
      "pregnancy_male": 0,
      "pregnancy_female": 10,
      "pregnancy_total": 10,
      "truancy_male": 30,
      "truancy_female": 21,
      "truancy_total": 51,
      "total_male": 33,
      "total_female": 33,
      "grand_total": 66,
      "%of Total Enrolment": 2
    },
    {
      "region": "Mtwara",
      "council": "Newala TC",
      "death_male": 1,
      "death_female": 1,
      "death_total": 2,
      "indiscipline_male": 8,
      "indiscipline_female": 0,
      "indiscipline_total": 8,
      "pregnancy_male": 0,
      "pregnancy_female": 8,
      "pregnancy_total": 8,
      "truancy_male": 55,
      "truancy_female": 29,
      "truancy_total": 84,
      "total_male": 64,
      "total_female": 38,
      "grand_total": 102,
      "%of Total Enrolment": 2.8
    },
    {
      "region": "Mtwara",
      "council": "Tandahimba",
      "death_male": 3,
      "death_female": 6,
      "death_total": 9,
      "indiscipline_male": 2,
      "indiscipline_female": 2,
      "indiscipline_total": 4,
      "pregnancy_male": 0,
      "pregnancy_female": 31,
      "pregnancy_total": 31,
      "truancy_male": 346,
      "truancy_female": 261,
      "truancy_total": 607,
      "total_male": 351,
      "total_female": 300,
      "grand_total": 651,
      "%of Total Enrolment": 8.7
    },
    {
      "region": "Mwanza",
      "council": "Buchosa",
      "death_male": 2,
      "death_female": 4,
      "death_total": 6,
      "indiscipline_male": 3,
      "indiscipline_female": 0,
      "indiscipline_total": 3,
      "pregnancy_male": 0,
      "pregnancy_female": 31,
      "pregnancy_total": 31,
      "truancy_male": 497,
      "truancy_female": 405,
      "truancy_total": 902,
      "total_male": 502,
      "total_female": 440,
      "grand_total": 942,
      "%of Total Enrolment": 9.8
    },
    {
      "region": "Mwanza",
      "council": "Ilemela MC",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 25,
      "indiscipline_female": 20,
      "indiscipline_total": 45,
      "pregnancy_male": 0,
      "pregnancy_female": 23,
      "pregnancy_total": 23,
      "truancy_male": 165,
      "truancy_female": 131,
      "truancy_total": 296,
      "total_male": 190,
      "total_female": 174,
      "grand_total": 364,
      "%of Total Enrolment": 1.5
    },
    {
      "region": "Mwanza",
      "council": "Kwimba",
      "death_male": 4,
      "death_female": 1,
      "death_total": 5,
      "indiscipline_male": 8,
      "indiscipline_female": 5,
      "indiscipline_total": 13,
      "pregnancy_male": 0,
      "pregnancy_female": 55,
      "pregnancy_total": 55,
      "truancy_male": 546,
      "truancy_female": 427,
      "truancy_total": 973,
      "total_male": 558,
      "total_female": 488,
      "grand_total": 1046,
      "%of Total Enrolment": 7.9
    },
    {
      "region": "Mwanza",
      "council": "Magu",
      "death_male": 4,
      "death_female": 1,
      "death_total": 5,
      "indiscipline_male": 16,
      "indiscipline_female": 8,
      "indiscipline_total": 24,
      "pregnancy_male": 0,
      "pregnancy_female": 26,
      "pregnancy_total": 26,
      "truancy_male": 370,
      "truancy_female": 297,
      "truancy_total": 667,
      "total_male": 390,
      "total_female": 332,
      "grand_total": 722,
      "%of Total Enrolment": 5.5
    },
    {
      "region": "Mwanza",
      "council": "Misungwi",
      "death_male": 6,
      "death_female": 1,
      "death_total": 7,
      "indiscipline_male": 2,
      "indiscipline_female": 13,
      "indiscipline_total": 15,
      "pregnancy_male": 0,
      "pregnancy_female": 40,
      "pregnancy_total": 40,
      "truancy_male": 468,
      "truancy_female": 454,
      "truancy_total": 922,
      "total_male": 476,
      "total_female": 508,
      "grand_total": 984,
      "%of Total Enrolment": 9.3
    },
    {
      "region": "Mwanza",
      "council": "Mwanza CC",
      "death_male": 11,
      "death_female": 4,
      "death_total": 15,
      "indiscipline_male": 14,
      "indiscipline_female": 25,
      "indiscipline_total": 39,
      "pregnancy_male": 0,
      "pregnancy_female": 44,
      "pregnancy_total": 44,
      "truancy_male": 218,
      "truancy_female": 174,
      "truancy_total": 392,
      "total_male": 243,
      "total_female": 247,
      "grand_total": 490,
      "%of Total Enrolment": 1.5
    },
    {
      "region": "Mwanza",
      "council": "Sengerema",
      "death_male": 3,
      "death_female": 6,
      "death_total": 9,
      "indiscipline_male": 11,
      "indiscipline_female": 0,
      "indiscipline_total": 11,
      "pregnancy_male": 0,
      "pregnancy_female": 55,
      "pregnancy_total": 55,
      "truancy_male": 342,
      "truancy_female": 217,
      "truancy_total": 559,
      "total_male": 356,
      "total_female": 278,
      "grand_total": 634,
      "%of Total Enrolment": 4
    },
    {
      "region": "Mwanza",
      "council": "Ukerewe",
      "death_male": 4,
      "death_female": 3,
      "death_total": 7,
      "indiscipline_male": 12,
      "indiscipline_female": 6,
      "indiscipline_total": 18,
      "pregnancy_male": 0,
      "pregnancy_female": 75,
      "pregnancy_total": 75,
      "truancy_male": 374,
      "truancy_female": 283,
      "truancy_total": 657,
      "total_male": 390,
      "total_female": 367,
      "grand_total": 757,
      "%of Total Enrolment": 4.8
    },
    {
      "region": "Njombe",
      "council": "Ludewa",
      "death_male": 0,
      "death_female": 1,
      "death_total": 1,
      "indiscipline_male": 8,
      "indiscipline_female": 6,
      "indiscipline_total": 14,
      "pregnancy_male": 0,
      "pregnancy_female": 19,
      "pregnancy_total": 19,
      "truancy_male": 92,
      "truancy_female": 58,
      "truancy_total": 150,
      "total_male": 100,
      "total_female": 84,
      "grand_total": 184,
      "%of Total Enrolment": 3.1
    },
    {
      "region": "Njombe",
      "council": "Makambako TC",
      "death_male": 2,
      "death_female": 1,
      "death_total": 3,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 11,
      "pregnancy_total": 11,
      "truancy_male": 77,
      "truancy_female": 51,
      "truancy_total": 128,
      "total_male": 79,
      "total_female": 63,
      "grand_total": 142,
      "%of Total Enrolment": 2.3
    },
    {
      "region": "Njombe",
      "council": "Makete",
      "death_male": 1,
      "death_female": 3,
      "death_total": 4,
      "indiscipline_male": 16,
      "indiscipline_female": 1,
      "indiscipline_total": 17,
      "pregnancy_male": 0,
      "pregnancy_female": 20,
      "pregnancy_total": 20,
      "truancy_male": 154,
      "truancy_female": 85,
      "truancy_total": 239,
      "total_male": 171,
      "total_female": 109,
      "grand_total": 280,
      "%of Total Enrolment": 5.2
    },
    {
      "region": "Njombe",
      "council": "Njombe",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 0,
      "indiscipline_female": 2,
      "indiscipline_total": 2,
      "pregnancy_male": 0,
      "pregnancy_female": 6,
      "pregnancy_total": 6,
      "truancy_male": 135,
      "truancy_female": 107,
      "truancy_total": 242,
      "total_male": 135,
      "total_female": 115,
      "grand_total": 250,
      "%of Total Enrolment": 6.1
    },
    {
      "region": "Njombe",
      "council": "Njombe TC",
      "death_male": 3,
      "death_female": 0,
      "death_total": 3,
      "indiscipline_male": 24,
      "indiscipline_female": 19,
      "indiscipline_total": 43,
      "pregnancy_male": 0,
      "pregnancy_female": 19,
      "pregnancy_total": 19,
      "truancy_male": 175,
      "truancy_female": 117,
      "truancy_total": 292,
      "total_male": 202,
      "total_female": 155,
      "grand_total": 357,
      "%of Total Enrolment": 3.6
    },
    {
      "region": "Njombe",
      "council": "Wanging'ombe",
      "death_male": 4,
      "death_female": 1,
      "death_total": 5,
      "indiscipline_male": 2,
      "indiscipline_female": 10,
      "indiscipline_total": 12,
      "pregnancy_male": 0,
      "pregnancy_female": 10,
      "pregnancy_total": 10,
      "truancy_male": 274,
      "truancy_female": 212,
      "truancy_total": 486,
      "total_male": 280,
      "total_female": 233,
      "grand_total": 513,
      "%of Total Enrolment": 5.7
    },
    {
      "region": "Pwani",
      "council": "Bagamoyo",
      "death_male": 1,
      "death_female": 2,
      "death_total": 3,
      "indiscipline_male": 0,
      "indiscipline_female": 5,
      "indiscipline_total": 5,
      "pregnancy_male": 0,
      "pregnancy_female": 4,
      "pregnancy_total": 4,
      "truancy_male": 47,
      "truancy_female": 25,
      "truancy_total": 72,
      "total_male": 48,
      "total_female": 36,
      "grand_total": 84,
      "%of Total Enrolment": 0.8
    },
    {
      "region": "Pwani",
      "council": "Chalinze",
      "death_male": 0,
      "death_female": 1,
      "death_total": 1,
      "indiscipline_male": 6,
      "indiscipline_female": 4,
      "indiscipline_total": 10,
      "pregnancy_male": 0,
      "pregnancy_female": 14,
      "pregnancy_total": 14,
      "truancy_male": 132,
      "truancy_female": 159,
      "truancy_total": 291,
      "total_male": 138,
      "total_female": 178,
      "grand_total": 316,
      "%of Total Enrolment": 3.2
    },
    {
      "region": "Pwani",
      "council": "Kibaha",
      "death_male": 2,
      "death_female": 4,
      "death_total": 6,
      "indiscipline_male": 1,
      "indiscipline_female": 0,
      "indiscipline_total": 1,
      "pregnancy_male": 0,
      "pregnancy_female": 10,
      "pregnancy_total": 10,
      "truancy_male": 113,
      "truancy_female": 106,
      "truancy_total": 219,
      "total_male": 116,
      "total_female": 120,
      "grand_total": 236,
      "%of Total Enrolment": 4.2
    },
    {
      "region": "Pwani",
      "council": "Kibaha TC",
      "death_male": 9,
      "death_female": 3,
      "death_total": 12,
      "indiscipline_male": 5,
      "indiscipline_female": 1,
      "indiscipline_total": 6,
      "pregnancy_male": 0,
      "pregnancy_female": 7,
      "pregnancy_total": 7,
      "truancy_male": 75,
      "truancy_female": 88,
      "truancy_total": 163,
      "total_male": 89,
      "total_female": 99,
      "grand_total": 188,
      "%of Total Enrolment": 1.8
    },
    {
      "region": "Pwani",
      "council": "Kibiti",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 0,
      "pregnancy_total": 0,
      "truancy_male": 0,
      "truancy_female": 0,
      "truancy_total": 0,
      "total_male": 0,
      "total_female": 0,
      "grand_total": 0,
      "%of Total Enrolment": 0
    },
    {
      "region": "Pwani",
      "council": "Kisarawe",
      "death_male": 0,
      "death_female": 2,
      "death_total": 2,
      "indiscipline_male": 3,
      "indiscipline_female": 1,
      "indiscipline_total": 4,
      "pregnancy_male": 0,
      "pregnancy_female": 11,
      "pregnancy_total": 11,
      "truancy_male": 133,
      "truancy_female": 70,
      "truancy_total": 203,
      "total_male": 136,
      "total_female": 84,
      "grand_total": 220,
      "%of Total Enrolment": 3.7
    },
    {
      "region": "Pwani",
      "council": "Mafia",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 5,
      "pregnancy_total": 5,
      "truancy_male": 8,
      "truancy_female": 10,
      "truancy_total": 18,
      "total_male": 8,
      "total_female": 15,
      "grand_total": 23,
      "%of Total Enrolment": 1.3
    },
    {
      "region": "Pwani",
      "council": "Mkuranga",
      "death_male": 2,
      "death_female": 0,
      "death_total": 2,
      "indiscipline_male": 9,
      "indiscipline_female": 5,
      "indiscipline_total": 14,
      "pregnancy_male": 0,
      "pregnancy_female": 9,
      "pregnancy_total": 9,
      "truancy_male": 209,
      "truancy_female": 217,
      "truancy_total": 426,
      "total_male": 220,
      "total_female": 231,
      "grand_total": 451,
      "%of Total Enrolment": 3.6
    },
    {
      "region": "Pwani",
      "council": "Rufiji",
      "death_male": 6,
      "death_female": 0,
      "death_total": 6,
      "indiscipline_male": 1,
      "indiscipline_female": 0,
      "indiscipline_total": 1,
      "pregnancy_male": 0,
      "pregnancy_female": 18,
      "pregnancy_total": 18,
      "truancy_male": 107,
      "truancy_female": 65,
      "truancy_total": 172,
      "total_male": 114,
      "total_female": 83,
      "grand_total": 197,
      "%of Total Enrolment": 2.5
    },
    {
      "region": "Rukwa",
      "council": "Kalambo",
      "death_male": 1,
      "death_female": 0,
      "death_total": 1,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 26,
      "pregnancy_total": 26,
      "truancy_male": 277,
      "truancy_female": 177,
      "truancy_total": 454,
      "total_male": 278,
      "total_female": 203,
      "grand_total": 481,
      "%of Total Enrolment": 10
    },
    {
      "region": "Rukwa",
      "council": "Nkasi",
      "death_male": 1,
      "death_female": 2,
      "death_total": 3,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 74,
      "pregnancy_total": 74,
      "truancy_male": 233,
      "truancy_female": 136,
      "truancy_total": 369,
      "total_male": 234,
      "total_female": 212,
      "grand_total": 446,
      "%of Total Enrolment": 6.8
    },
    {
      "region": "Rukwa",
      "council": "Sumbawanga",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 7,
      "indiscipline_female": 1,
      "indiscipline_total": 8,
      "pregnancy_male": 0,
      "pregnancy_female": 8,
      "pregnancy_total": 8,
      "truancy_male": 97,
      "truancy_female": 63,
      "truancy_total": 160,
      "total_male": 104,
      "total_female": 72,
      "grand_total": 176,
      "%of Total Enrolment": 3.2
    },
    {
      "region": "Rukwa",
      "council": "Sumbawanga MC",
      "death_male": 5,
      "death_female": 1,
      "death_total": 6,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 39,
      "pregnancy_total": 39,
      "truancy_male": 98,
      "truancy_female": 78,
      "truancy_total": 176,
      "total_male": 103,
      "total_female": 118,
      "grand_total": 221,
      "%of Total Enrolment": 1.7
    },
    {
      "region": "Ruvuma",
      "council": "Madaba",
      "death_male": 1,
      "death_female": 0,
      "death_total": 1,
      "indiscipline_male": 2,
      "indiscipline_female": 1,
      "indiscipline_total": 3,
      "pregnancy_male": 0,
      "pregnancy_female": 10,
      "pregnancy_total": 10,
      "truancy_male": 35,
      "truancy_female": 49,
      "truancy_total": 84,
      "total_male": 38,
      "total_female": 60,
      "grand_total": 98,
      "%of Total Enrolment": 3.7
    },
    {
      "region": "Ruvuma",
      "council": "Mbinga",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 16,
      "indiscipline_female": 6,
      "indiscipline_total": 22,
      "pregnancy_male": 0,
      "pregnancy_female": 55,
      "pregnancy_total": 55,
      "truancy_male": 278,
      "truancy_female": 192,
      "truancy_total": 470,
      "total_male": 294,
      "total_female": 253,
      "grand_total": 547,
      "%of Total Enrolment": 4.9
    },
    {
      "region": "Ruvuma",
      "council": "Mbinga TC",
      "death_male": 2,
      "death_female": 0,
      "death_total": 2,
      "indiscipline_male": 1,
      "indiscipline_female": 1,
      "indiscipline_total": 2,
      "pregnancy_male": 0,
      "pregnancy_female": 13,
      "pregnancy_total": 13,
      "truancy_male": 74,
      "truancy_female": 51,
      "truancy_total": 125,
      "total_male": 77,
      "total_female": 65,
      "grand_total": 142,
      "%of Total Enrolment": 2.8
    },
    {
      "region": "Ruvuma",
      "council": "Namtumbo",
      "death_male": 2,
      "death_female": 0,
      "death_total": 2,
      "indiscipline_male": 37,
      "indiscipline_female": 0,
      "indiscipline_total": 37,
      "pregnancy_male": 0,
      "pregnancy_female": 62,
      "pregnancy_total": 62,
      "truancy_male": 222,
      "truancy_female": 177,
      "truancy_total": 399,
      "total_male": 261,
      "total_female": 239,
      "grand_total": 500,
      "%of Total Enrolment": 6.7
    },
    {
      "region": "Ruvuma",
      "council": "Nyasa",
      "death_male": 0,
      "death_female": 1,
      "death_total": 1,
      "indiscipline_male": 2,
      "indiscipline_female": 3,
      "indiscipline_total": 5,
      "pregnancy_male": 0,
      "pregnancy_female": 52,
      "pregnancy_total": 52,
      "truancy_male": 129,
      "truancy_female": 100,
      "truancy_total": 229,
      "total_male": 131,
      "total_female": 156,
      "grand_total": 287,
      "%of Total Enrolment": 6.5
    },
    {
      "region": "Ruvuma",
      "council": "Songea",
      "death_male": 2,
      "death_female": 0,
      "death_total": 2,
      "indiscipline_male": 2,
      "indiscipline_female": 3,
      "indiscipline_total": 5,
      "pregnancy_male": 0,
      "pregnancy_female": 14,
      "pregnancy_total": 14,
      "truancy_male": 65,
      "truancy_female": 69,
      "truancy_total": 134,
      "total_male": 69,
      "total_female": 86,
      "grand_total": 155,
      "%of Total Enrolment": 3.1
    },
    {
      "region": "Ruvuma",
      "council": "Songea MC",
      "death_male": 1,
      "death_female": 2,
      "death_total": 3,
      "indiscipline_male": 3,
      "indiscipline_female": 3,
      "indiscipline_total": 6,
      "pregnancy_male": 0,
      "pregnancy_female": 21,
      "pregnancy_total": 21,
      "truancy_male": 29,
      "truancy_female": 11,
      "truancy_total": 40,
      "total_male": 33,
      "total_female": 37,
      "grand_total": 70,
      "%of Total Enrolment": 0.5
    },
    {
      "region": "Ruvuma",
      "council": "Tunduru",
      "death_male": 6,
      "death_female": 2,
      "death_total": 8,
      "indiscipline_male": 24,
      "indiscipline_female": 10,
      "indiscipline_total": 34,
      "pregnancy_male": 0,
      "pregnancy_female": 44,
      "pregnancy_total": 44,
      "truancy_male": 233,
      "truancy_female": 179,
      "truancy_total": 412,
      "total_male": 263,
      "total_female": 235,
      "grand_total": 498,
      "%of Total Enrolment": 6.1
    },
    {
      "region": "Shinyanga",
      "council": "Kahama TC",
      "death_male": 3,
      "death_female": 1,
      "death_total": 4,
      "indiscipline_male": 8,
      "indiscipline_female": 0,
      "indiscipline_total": 8,
      "pregnancy_male": 0,
      "pregnancy_female": 3,
      "pregnancy_total": 3,
      "truancy_male": 146,
      "truancy_female": 143,
      "truancy_total": 289,
      "total_male": 157,
      "total_female": 147,
      "grand_total": 304,
      "%of Total Enrolment": 2.6
    },
    {
      "region": "Shinyanga",
      "council": "Kishapu",
      "death_male": 2,
      "death_female": 3,
      "death_total": 5,
      "indiscipline_male": 2,
      "indiscipline_female": 0,
      "indiscipline_total": 2,
      "pregnancy_male": 0,
      "pregnancy_female": 26,
      "pregnancy_total": 26,
      "truancy_male": 157,
      "truancy_female": 138,
      "truancy_total": 295,
      "total_male": 161,
      "total_female": 167,
      "grand_total": 328,
      "%of Total Enrolment": 3.7
    },
    {
      "region": "Shinyanga",
      "council": "Msalala",
      "death_male": 6,
      "death_female": 1,
      "death_total": 7,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 63,
      "pregnancy_total": 63,
      "truancy_male": 594,
      "truancy_female": 427,
      "truancy_total": 1021,
      "total_male": 600,
      "total_female": 491,
      "grand_total": 1091,
      "%of Total Enrolment": 15
    },
    {
      "region": "Shinyanga",
      "council": "Shinyanga",
      "death_male": 2,
      "death_female": 3,
      "death_total": 5,
      "indiscipline_male": 6,
      "indiscipline_female": 5,
      "indiscipline_total": 11,
      "pregnancy_male": 0,
      "pregnancy_female": 40,
      "pregnancy_total": 40,
      "truancy_male": 241,
      "truancy_female": 186,
      "truancy_total": 427,
      "total_male": 249,
      "total_female": 234,
      "grand_total": 483,
      "%of Total Enrolment": 5.8
    },
    {
      "region": "Shinyanga",
      "council": "Shinyanga MC",
      "death_male": 2,
      "death_female": 1,
      "death_total": 3,
      "indiscipline_male": 5,
      "indiscipline_female": 0,
      "indiscipline_total": 5,
      "pregnancy_male": 0,
      "pregnancy_female": 26,
      "pregnancy_total": 26,
      "truancy_male": 52,
      "truancy_female": 44,
      "truancy_total": 96,
      "total_male": 59,
      "total_female": 71,
      "grand_total": 130,
      "%of Total Enrolment": 1.5
    },
    {
      "region": "Shinyanga",
      "council": "Ushetu",
      "death_male": 2,
      "death_female": 1,
      "death_total": 3,
      "indiscipline_male": 4,
      "indiscipline_female": 0,
      "indiscipline_total": 4,
      "pregnancy_male": 0,
      "pregnancy_female": 24,
      "pregnancy_total": 24,
      "truancy_male": 205,
      "truancy_female": 136,
      "truancy_total": 341,
      "total_male": 211,
      "total_female": 161,
      "grand_total": 372,
      "%of Total Enrolment": 7.5
    },
    {
      "region": "Simiyu",
      "council": "Bariadi",
      "death_male": 3,
      "death_female": 0,
      "death_total": 3,
      "indiscipline_male": 3,
      "indiscipline_female": 3,
      "indiscipline_total": 6,
      "pregnancy_male": 0,
      "pregnancy_female": 14,
      "pregnancy_total": 14,
      "truancy_male": 174,
      "truancy_female": 114,
      "truancy_total": 288,
      "total_male": 180,
      "total_female": 131,
      "grand_total": 311,
      "%of Total Enrolment": 5.2
    },
    {
      "region": "Simiyu",
      "council": "Bariadi TC",
      "death_male": 1,
      "death_female": 0,
      "death_total": 1,
      "indiscipline_male": 1,
      "indiscipline_female": 0,
      "indiscipline_total": 1,
      "pregnancy_male": 0,
      "pregnancy_female": 15,
      "pregnancy_total": 15,
      "truancy_male": 176,
      "truancy_female": 111,
      "truancy_total": 287,
      "total_male": 178,
      "total_female": 126,
      "grand_total": 304,
      "%of Total Enrolment": 4.7
    },
    {
      "region": "Simiyu",
      "council": "Busega",
      "death_male": 3,
      "death_female": 0,
      "death_total": 3,
      "indiscipline_male": 2,
      "indiscipline_female": 0,
      "indiscipline_total": 2,
      "pregnancy_male": 0,
      "pregnancy_female": 47,
      "pregnancy_total": 47,
      "truancy_male": 151,
      "truancy_female": 71,
      "truancy_total": 222,
      "total_male": 156,
      "total_female": 118,
      "grand_total": 274,
      "%of Total Enrolment": 2.8
    },
    {
      "region": "Simiyu",
      "council": "Itilima",
      "death_male": 3,
      "death_female": 1,
      "death_total": 4,
      "indiscipline_male": 12,
      "indiscipline_female": 3,
      "indiscipline_total": 15,
      "pregnancy_male": 0,
      "pregnancy_female": 1,
      "pregnancy_total": 1,
      "truancy_male": 307,
      "truancy_female": 180,
      "truancy_total": 487,
      "total_male": 322,
      "total_female": 185,
      "grand_total": 507,
      "%of Total Enrolment": 7.8
    },
    {
      "region": "Simiyu",
      "council": "Maswa",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 7,
      "indiscipline_female": 4,
      "indiscipline_total": 11,
      "pregnancy_male": 0,
      "pregnancy_female": 27,
      "pregnancy_total": 27,
      "truancy_male": 245,
      "truancy_female": 209,
      "truancy_total": 454,
      "total_male": 252,
      "total_female": 240,
      "grand_total": 492,
      "%of Total Enrolment": 4.9
    },
    {
      "region": "Simiyu",
      "council": "Meatu",
      "death_male": 2,
      "death_female": 2,
      "death_total": 4,
      "indiscipline_male": 1,
      "indiscipline_female": 2,
      "indiscipline_total": 3,
      "pregnancy_male": 0,
      "pregnancy_female": 12,
      "pregnancy_total": 12,
      "truancy_male": 138,
      "truancy_female": 155,
      "truancy_total": 293,
      "total_male": 141,
      "total_female": 171,
      "grand_total": 312,
      "%of Total Enrolment": 5.9
    },
    {
      "region": "Singida",
      "council": "Ikungi",
      "death_male": 1,
      "death_female": 9,
      "death_total": 10,
      "indiscipline_male": 9,
      "indiscipline_female": 9,
      "indiscipline_total": 18,
      "pregnancy_male": 0,
      "pregnancy_female": 23,
      "pregnancy_total": 23,
      "truancy_male": 184,
      "truancy_female": 121,
      "truancy_total": 305,
      "total_male": 194,
      "total_female": 162,
      "grand_total": 356,
      "%of Total Enrolment": 4.3
    },
    {
      "region": "Singida",
      "council": "Iramba",
      "death_male": 2,
      "death_female": 1,
      "death_total": 3,
      "indiscipline_male": 5,
      "indiscipline_female": 0,
      "indiscipline_total": 5,
      "pregnancy_male": 0,
      "pregnancy_female": 33,
      "pregnancy_total": 33,
      "truancy_male": 134,
      "truancy_female": 77,
      "truancy_total": 211,
      "total_male": 141,
      "total_female": 111,
      "grand_total": 252,
      "%of Total Enrolment": 3.8
    },
    {
      "region": "Singida",
      "council": "Itigi",
      "death_male": 1,
      "death_female": 0,
      "death_total": 1,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 18,
      "pregnancy_total": 18,
      "truancy_male": 21,
      "truancy_female": 7,
      "truancy_total": 28,
      "total_male": 22,
      "total_female": 25,
      "grand_total": 47,
      "%of Total Enrolment": 1.7
    },
    {
      "region": "Singida",
      "council": "Manyoni",
      "death_male": 2,
      "death_female": 4,
      "death_total": 6,
      "indiscipline_male": 2,
      "indiscipline_female": 2,
      "indiscipline_total": 4,
      "pregnancy_male": 0,
      "pregnancy_female": 33,
      "pregnancy_total": 33,
      "truancy_male": 57,
      "truancy_female": 47,
      "truancy_total": 104,
      "total_male": 61,
      "total_female": 86,
      "grand_total": 147,
      "%of Total Enrolment": 3.3
    },
    {
      "region": "Singida",
      "council": "Mkalama",
      "death_male": 0,
      "death_female": 2,
      "death_total": 2,
      "indiscipline_male": 1,
      "indiscipline_female": 0,
      "indiscipline_total": 1,
      "pregnancy_male": 0,
      "pregnancy_female": 22,
      "pregnancy_total": 22,
      "truancy_male": 85,
      "truancy_female": 54,
      "truancy_total": 139,
      "total_male": 86,
      "total_female": 78,
      "grand_total": 164,
      "%of Total Enrolment": 3.7
    },
    {
      "region": "Singida",
      "council": "Singida",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 5,
      "indiscipline_female": 4,
      "indiscipline_total": 9,
      "pregnancy_male": 0,
      "pregnancy_female": 19,
      "pregnancy_total": 19,
      "truancy_male": 255,
      "truancy_female": 249,
      "truancy_total": 504,
      "total_male": 260,
      "total_female": 272,
      "grand_total": 532,
      "%of Total Enrolment": 6.5
    },
    {
      "region": "Singida",
      "council": "Singida MC",
      "death_male": 1,
      "death_female": 2,
      "death_total": 3,
      "indiscipline_male": 8,
      "indiscipline_female": 0,
      "indiscipline_total": 8,
      "pregnancy_male": 0,
      "pregnancy_female": 12,
      "pregnancy_total": 12,
      "truancy_male": 85,
      "truancy_female": 90,
      "truancy_total": 175,
      "total_male": 94,
      "total_female": 104,
      "grand_total": 198,
      "%of Total Enrolment": 2.5
    },
    {
      "region": "Songwe",
      "council": "Ileje",
      "death_male": 1,
      "death_female": 0,
      "death_total": 1,
      "indiscipline_male": 2,
      "indiscipline_female": 8,
      "indiscipline_total": 10,
      "pregnancy_male": 0,
      "pregnancy_female": 20,
      "pregnancy_total": 20,
      "truancy_male": 60,
      "truancy_female": 68,
      "truancy_total": 128,
      "total_male": 63,
      "total_female": 96,
      "grand_total": 159,
      "%of Total Enrolment": 2.9
    },
    {
      "region": "Songwe",
      "council": "Mbozi",
      "death_male": 10,
      "death_female": 8,
      "death_total": 18,
      "indiscipline_male": 3,
      "indiscipline_female": 1,
      "indiscipline_total": 4,
      "pregnancy_male": 0,
      "pregnancy_female": 52,
      "pregnancy_total": 52,
      "truancy_male": 345,
      "truancy_female": 338,
      "truancy_total": 683,
      "total_male": 358,
      "total_female": 399,
      "grand_total": 757,
      "%of Total Enrolment": 3.4
    },
    {
      "region": "Songwe",
      "council": "Momba",
      "death_male": 2,
      "death_female": 0,
      "death_total": 2,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 1,
      "pregnancy_total": 1,
      "truancy_male": 115,
      "truancy_female": 44,
      "truancy_total": 159,
      "total_male": 117,
      "total_female": 45,
      "grand_total": 162,
      "%of Total Enrolment": 7.9
    },
    {
      "region": "Songwe",
      "council": "Songwe",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 0,
      "pregnancy_total": 0,
      "truancy_male": 0,
      "truancy_female": 0,
      "truancy_total": 0,
      "total_male": 0,
      "total_female": 0,
      "grand_total": 0,
      "%of Total Enrolment": 0
    },
    {
      "region": "Songwe",
      "council": "Tunduma TC",
      "death_male": 1,
      "death_female": 0,
      "death_total": 1,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 0,
      "pregnancy_total": 0,
      "truancy_male": 89,
      "truancy_female": 47,
      "truancy_total": 136,
      "total_male": 90,
      "total_female": 47,
      "grand_total": 137,
      "%of Total Enrolment": 3.5
    },
    {
      "region": "Tabora",
      "council": "Igunga",
      "death_male": 0,
      "death_female": 4,
      "death_total": 4,
      "indiscipline_male": 14,
      "indiscipline_female": 3,
      "indiscipline_total": 17,
      "pregnancy_male": 0,
      "pregnancy_female": 25,
      "pregnancy_total": 25,
      "truancy_male": 348,
      "truancy_female": 241,
      "truancy_total": 589,
      "total_male": 362,
      "total_female": 273,
      "grand_total": 635,
      "%of Total Enrolment": 6.4
    },
    {
      "region": "Tabora",
      "council": "Kaliua",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 1,
      "indiscipline_female": 0,
      "indiscipline_total": 1,
      "pregnancy_male": 0,
      "pregnancy_female": 21,
      "pregnancy_total": 21,
      "truancy_male": 433,
      "truancy_female": 180,
      "truancy_total": 613,
      "total_male": 434,
      "total_female": 201,
      "grand_total": 635,
      "%of Total Enrolment": 10.5
    },
    {
      "region": "Tabora",
      "council": "Nzega",
      "death_male": 0,
      "death_female": 1,
      "death_total": 1,
      "indiscipline_male": 4,
      "indiscipline_female": 0,
      "indiscipline_total": 4,
      "pregnancy_male": 0,
      "pregnancy_female": 7,
      "pregnancy_total": 7,
      "truancy_male": 329,
      "truancy_female": 280,
      "truancy_total": 609,
      "total_male": 333,
      "total_female": 288,
      "grand_total": 621,
      "%of Total Enrolment": 11.4
    },
    {
      "region": "Tabora",
      "council": "Nzega TC",
      "death_male": 0,
      "death_female": 1,
      "death_total": 1,
      "indiscipline_male": 8,
      "indiscipline_female": 3,
      "indiscipline_total": 11,
      "pregnancy_male": 0,
      "pregnancy_female": 1,
      "pregnancy_total": 1,
      "truancy_male": 32,
      "truancy_female": 27,
      "truancy_total": 59,
      "total_male": 40,
      "total_female": 32,
      "grand_total": 72,
      "%of Total Enrolment": 2.4
    },
    {
      "region": "Tabora",
      "council": "Sikonge",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 0,
      "indiscipline_female": 1,
      "indiscipline_total": 1,
      "pregnancy_male": 0,
      "pregnancy_female": 38,
      "pregnancy_total": 38,
      "truancy_male": 497,
      "truancy_female": 447,
      "truancy_total": 944,
      "total_male": 497,
      "total_female": 486,
      "grand_total": 983,
      "%of Total Enrolment": 14.7
    },
    {
      "region": "Tabora",
      "council": "Tabora MC",
      "death_male": 2,
      "death_female": 2,
      "death_total": 4,
      "indiscipline_male": 39,
      "indiscipline_female": 3,
      "indiscipline_total": 42,
      "pregnancy_male": 0,
      "pregnancy_female": 19,
      "pregnancy_total": 19,
      "truancy_male": 122,
      "truancy_female": 104,
      "truancy_total": 226,
      "total_male": 163,
      "total_female": 128,
      "grand_total": 291,
      "%of Total Enrolment": 2
    },
    {
      "region": "Tabora",
      "council": "Tabora/Uyui",
      "death_male": 3,
      "death_female": 0,
      "death_total": 3,
      "indiscipline_male": 0,
      "indiscipline_female": 1,
      "indiscipline_total": 1,
      "pregnancy_male": 0,
      "pregnancy_female": 12,
      "pregnancy_total": 12,
      "truancy_male": 732,
      "truancy_female": 636,
      "truancy_total": 1368,
      "total_male": 735,
      "total_female": 649,
      "grand_total": 1384,
      "%of Total Enrolment": 20.1
    },
    {
      "region": "Tabora",
      "council": "Urambo",
      "death_male": 2,
      "death_female": 0,
      "death_total": 2,
      "indiscipline_male": 4,
      "indiscipline_female": 0,
      "indiscipline_total": 4,
      "pregnancy_male": 0,
      "pregnancy_female": 20,
      "pregnancy_total": 20,
      "truancy_male": 126,
      "truancy_female": 87,
      "truancy_total": 213,
      "total_male": 132,
      "total_female": 107,
      "grand_total": 239,
      "%of Total Enrolment": 4.5
    },
    {
      "region": "Tanga",
      "council": "Bumbuli",
      "death_male": 1,
      "death_female": 1,
      "death_total": 2,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 8,
      "pregnancy_total": 8,
      "truancy_male": 144,
      "truancy_female": 126,
      "truancy_total": 270,
      "total_male": 145,
      "total_female": 135,
      "grand_total": 280,
      "%of Total Enrolment": 3.6
    },
    {
      "region": "Tanga",
      "council": "Handeni",
      "death_male": 2,
      "death_female": 3,
      "death_total": 5,
      "indiscipline_male": 5,
      "indiscipline_female": 0,
      "indiscipline_total": 5,
      "pregnancy_male": 0,
      "pregnancy_female": 32,
      "pregnancy_total": 32,
      "truancy_male": 260,
      "truancy_female": 224,
      "truancy_total": 484,
      "total_male": 267,
      "total_female": 259,
      "grand_total": 526,
      "%of Total Enrolment": 7.1
    },
    {
      "region": "Tanga",
      "council": "Handeni TC",
      "death_male": 2,
      "death_female": 0,
      "death_total": 2,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 1,
      "pregnancy_total": 1,
      "truancy_male": 33,
      "truancy_female": 55,
      "truancy_total": 88,
      "total_male": 35,
      "total_female": 56,
      "grand_total": 91,
      "%of Total Enrolment": 2.2
    },
    {
      "region": "Tanga",
      "council": "Kilindi",
      "death_male": 6,
      "death_female": 4,
      "death_total": 10,
      "indiscipline_male": 1,
      "indiscipline_female": 0,
      "indiscipline_total": 1,
      "pregnancy_male": 0,
      "pregnancy_female": 56,
      "pregnancy_total": 56,
      "truancy_male": 223,
      "truancy_female": 248,
      "truancy_total": 471,
      "total_male": 230,
      "total_female": 308,
      "grand_total": 538,
      "%of Total Enrolment": 8.6
    },
    {
      "region": "Tanga",
      "council": "Korogwe",
      "death_male": 4,
      "death_female": 1,
      "death_total": 5,
      "indiscipline_male": 1,
      "indiscipline_female": 0,
      "indiscipline_total": 1,
      "pregnancy_male": 0,
      "pregnancy_female": 24,
      "pregnancy_total": 24,
      "truancy_male": 227,
      "truancy_female": 154,
      "truancy_total": 381,
      "total_male": 232,
      "total_female": 179,
      "grand_total": 411,
      "%of Total Enrolment": 4
    },
    {
      "region": "Tanga",
      "council": "Korogwe TC",
      "death_male": 2,
      "death_female": 0,
      "death_total": 2,
      "indiscipline_male": 10,
      "indiscipline_female": 9,
      "indiscipline_total": 19,
      "pregnancy_male": 0,
      "pregnancy_female": 12,
      "pregnancy_total": 12,
      "truancy_male": 79,
      "truancy_female": 73,
      "truancy_total": 152,
      "total_male": 91,
      "total_female": 94,
      "grand_total": 185,
      "%of Total Enrolment": 3.4
    },
    {
      "region": "Tanga",
      "council": "Lushoto",
      "death_male": 5,
      "death_female": 4,
      "death_total": 9,
      "indiscipline_male": 3,
      "indiscipline_female": 5,
      "indiscipline_total": 8,
      "pregnancy_male": 0,
      "pregnancy_female": 19,
      "pregnancy_total": 19,
      "truancy_male": 304,
      "truancy_female": 382,
      "truancy_total": 686,
      "total_male": 312,
      "total_female": 410,
      "grand_total": 722,
      "%of Total Enrolment": 4.6
    },
    {
      "region": "Tanga",
      "council": "Mkinga",
      "death_male": 1,
      "death_female": 1,
      "death_total": 2,
      "indiscipline_male": 0,
      "indiscipline_female": 0,
      "indiscipline_total": 0,
      "pregnancy_male": 0,
      "pregnancy_female": 7,
      "pregnancy_total": 7,
      "truancy_male": 146,
      "truancy_female": 125,
      "truancy_total": 271,
      "total_male": 147,
      "total_female": 133,
      "grand_total": 280,
      "%of Total Enrolment": 6.5
    },
    {
      "region": "Tanga",
      "council": "Muheza",
      "death_male": 2,
      "death_female": 1,
      "death_total": 3,
      "indiscipline_male": 1,
      "indiscipline_female": 0,
      "indiscipline_total": 1,
      "pregnancy_male": 0,
      "pregnancy_female": 27,
      "pregnancy_total": 27,
      "truancy_male": 244,
      "truancy_female": 215,
      "truancy_total": 459,
      "total_male": 247,
      "total_female": 243,
      "grand_total": 490,
      "%of Total Enrolment": 4.7
    },
    {
      "region": "Tanga",
      "council": "Pangani",
      "death_male": 0,
      "death_female": 0,
      "death_total": 0,
      "indiscipline_male": 3,
      "indiscipline_female": 0,
      "indiscipline_total": 3,
      "pregnancy_male": 0,
      "pregnancy_female": 10,
      "pregnancy_total": 10,
      "truancy_male": 39,
      "truancy_female": 27,
      "truancy_total": 66,
      "total_male": 42,
      "total_female": 37,
      "grand_total": 79,
      "%of Total Enrolment": 3.1
    },
    {
      "region": "Tanga",
      "council": "Tanga CC",
      "death_male": 6,
      "death_female": 3,
      "death_total": 9,
      "indiscipline_male": 6,
      "indiscipline_female": 0,
      "indiscipline_total": 6,
      "pregnancy_male": 0,
      "pregnancy_female": 10,
      "pregnancy_total": 10,
      "truancy_male": 106,
      "truancy_female": 95,
      "truancy_total": 201,
      "total_male": 118,
      "total_female": 108,
      "grand_total": 226,
      "%of Total Enrolment": 1
    },
    {
      "region": "Tanga",
      "council": "grand_total",
      "death_male": 471,
      "death_female": 318,
      "death_total": 789,
      "indiscipline_male": 1205,
      "indiscipline_female": 624,
      "indiscipline_total": 1829,
      "pregnancy_male": 0,
      "pregnancy_female": 4442,
      "pregnancy_total": 4442,
      "truancy_male": 31959,
      "truancy_female": 24884,
      "truancy_total": 56843,
      "total_male": 33635,
      "total_female": 30268,
      "grand_total": 63903,
      "%of Total Enrolment": ""
    }
  ]